import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static const List<Locale> supportedLocales = [
    Locale('tr', 'TR'),
    Locale('en', 'US'),
  ];

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Cinema+',
      'tagline': 'WHAT TO WATCH?',
      'profile_about': 'About App',
      'profile_about_desc': 'Version, author and application info',
      'profile_about_title': 'About Cinema+ | What to Watch',
      'profile_about_content':
          'Cinema+ is your personal companion to discover movies and TV shows, match your taste with friends, and build your unique Cinema DNA.',
      'profile_about_author': 'Author',
      'profile_about_version': 'Version',
      'tmdb_attribution':
          'This product uses the TMDB API but is not endorsed or certified by TMDB.',
      'tab_browse': 'Browse',
      'tab_swipe': 'Rate',
      'tab_match': 'Match',
      'tab_together': 'Together',
      'together_match': 'Match',
      'together_friends': 'Friends',
      'together_desc': 'Discover, match and share with friends.',
      'together_social_title': 'Social & Friends',
      'together_social_desc': 'Friends, requests and activity feed',
      'together_friend_match_title': 'Friend Match',
      'together_friend_match_desc': 'See shared likes and recommendations',
      'together_couch_title': 'Couch Mode',
      'together_couch_desc': 'On one phone',
      'together_similar_title': 'Find Similar',
      'together_similar_desc': 'Discover titles similar to one you love',
      'tab_search': 'Search',
      'tab_profile': 'Profile',

      // Global top bar & menu
      'menu_social': 'Social',
      'menu_preferences': 'Preferences',
      'menu_account': 'Account',
      'menu_my_friends': 'My Friends',
      'menu_requests': 'Friend Requests',
      'menu_activity': 'Activity Feed',
      'menu_top_lists': 'Top Lists',
      'menu_my_profile': 'My Profile',
      'theme_dark': 'Dark',
      'theme_light': 'Light',

      // Library (showroom)
      'library_title': 'Your Library',
      'profile_cinema_identity': 'Your Cinema Identity',
      'danger_zone': 'Danger Zone',
      'sort_added': 'Added',
      'sort_rating': 'Rating',
      'sort_year': 'Year',
      'sort_my_rating': 'My Rating',
      'library_rated_empty_title': 'No ratings yet',
      'library_rated_empty_desc':
          'Rate movies and shows to build your history.',

      // Onboarding
      'onboarding_loading': 'Preparing...',
      'onboarding_quick_rating': 'Quick rating',
      'onboarding_skip': 'Skip',
      'onboarding_not_watched': 'Not Watched',
      'onboarding_title_movie_genres': 'Which movie genres do you like?',
      'onboarding_title_tv_genres': 'Which TV show genres do you like?',
      'onboarding_title_fav_movies': 'Select your top 3 favorite movies',
      'onboarding_title_fav_tvs': 'Select your top 3 favorite TV shows',
      'onboarding_title_rating': 'Quick Rating',
      'onboarding_search_hint': 'Search...',
      'onboarding_fav_desc': 'Optional — you can add up to 3 favorites.',
      'onboarding_next': 'Continue',
      'onboarding_finish': 'Start',
      'onboarding_selected': 'selected',
      'onboarding_movie': 'Movie',
      'onboarding_tv': 'TV Show',
      'onboarding_done': 'Done',
      'swipe_recommended': 'For You',

      // Profile
      'profile_reset_title': 'Reset All Data',
      'profile_reset_content':
          'Ratings, reviews, watchlist, preferences, and cloud backups will be permanently reset, and you will be logged out. Continue?',
      'profile_cancel': 'Cancel',
      'profile_reset': 'Reset',
      'profile_reset_failed_title': 'Reset Failed',
      'profile_reset_failed_content':
          'Failed to delete cloud data. Please check your connection and try again.',
      'ok': 'OK',
      'auth_title_login': 'Sign In',
      'auth_title_register': 'Sign Up',
      'auth_email': 'Email Address',
      'auth_password': 'Password',
      'auth_display_name': 'Display Name',
      'auth_button_login': 'Login',
      'auth_or': 'or',
      'auth_google_button': 'Continue with Google',
      'auth_button_register': 'Register',
      'auth_toggle_to_register': "Don't have an account? Sign Up",
      'auth_toggle_to_login': 'Already have an account? Sign In',
      'sync_title': 'Cloud Backup',
      'sync_desc':
          'Keep your watchlist, ratings, and history synced safely in the cloud.',
      'sync_now': 'Sync Now',
      'sync_success': 'Synchronized successfully',
      'sync_last': 'Last synced: ',
      'auth_logout': 'Sign Out',
      'auth_logout_confirm':
          'Sign out of your account? Your ratings and lists stay on this device.',
      'auth_logout_wipe_local': 'Also remove data from this device',
      'session_expired_message':
          'Your session has expired. Your data is safe on this device. Please sign in again.',
      'auth_conflict_title': 'Account Conflict',
      'auth_conflict_desc':
          'This device has local data (ratings, lists) that is not yet linked to the account you are signing into — it may have been created as a guest or with another account. "Delete Local Data" will permanently erase it from this device. How would you like to proceed?',
      'auth_conflict_merge': 'Merge with this Account',
      'auth_conflict_delete': 'Delete Local Data & Load Cloud Data',
      'auth_conflict_cancel': 'Cancel Login',
      'auth_delete_account': 'Delete Account',
      'auth_delete_confirm':
          'This will permanently delete your account and all associated cloud data. Are you sure?',
      'auth_delete_ack': 'I understand this action cannot be undone.',
      'auth_delete_done':
          'Your account and cloud data have been permanently deleted.',
      'auth_forgot_password_link': 'Forgot Password?',
      'auth_forgot_title': 'Forgot Password',
      'change_password_title': 'Change Password',
      'change_password_desc':
          'You will be logged out of all devices on success.',
      'change_password_old_password': 'Current Password',
      'change_password_new_password': 'New Password',
      'change_password_confirm_password': 'Confirm New Password',
      'change_password_button': 'Update Password',
      'change_password_error_mismatch': 'New passwords do not match.',
      'change_password_error_short': 'Password must be at least 6 characters.',
      'change_password_success': 'Password changed successfully.',
      'google_unlink_title': 'Unlink Google Account',
      'google_unlink_desc': 'Enter your account password to continue.',
      'google_unlink_button': 'Unlink Google',
      'google_unlink_success': 'Google account unlinked.',
      'auth_err_google_unlink_failed': 'Could not unlink Google account.',
      'auth_forgot_email_desc':
          'Enter your registered email address to receive a password reset code.',
      'auth_forgot_code_title': 'Verify Code',
      'auth_forgot_code_desc':
          'Enter the 6-digit verification code sent to your email.',
      'auth_forgot_reset_title': 'Reset Password',
      'auth_forgot_reset_desc':
          'Set a new password of at least 8 characters for your account.',
      'auth_forgot_label_code': '6-Digit Verification Code',
      'auth_forgot_label_new_pass': 'New Password',
      'auth_forgot_btn_send_code': 'Send Code',
      'auth_forgot_btn_verify': 'Verify Code',
      'auth_forgot_btn_reset': 'Update Password',
      'auth_forgot_btn_back': 'Back',
      'auth_forgot_err_name_empty': 'Name field cannot be empty.',
      'auth_forgot_err_email_invalid': 'Enter a valid email.',
      'auth_forgot_err_code_length': 'Enter the complete 6-digit code.',
      'auth_forgot_err_pass_length': 'Password must be at least 8 characters.',
      'auth_forgot_success_reset':
          'Your password has been successfully reset. You can now sign in with your new password.',
      'auth_err_google_not_configured':
          'Google sign-in is not configured for this build.',
      'auth_err_google_token_failed': 'Failed to retrieve Google ID token.',
      'auth_err_google_failed': 'Google sign-in failed. Please try again.',
      'auth_err_register_failed':
          'Registration failed. Please check your connection.',
      'auth_err_login_failed': 'Login failed. Please check your connection.',
      'auth_err_delete_failed': 'Failed to delete account. Please try again.',
      'auth_err_change_pass_failed':
          'Failed to change password. Please try again.',
      'auth_err_email_exists': 'This email is already registered.',
      'auth_err_invalid_credentials': 'Invalid email or password.',
      'auth_err_wrong_password': 'Current password is incorrect.',
      'auth_err_user_not_found': 'User not found.',
      'auth_err_forgot_send_failed':
          'Failed to send reset code. Please check your connection.',
      'auth_err_verify_code_failed':
          'Verification code is invalid. Please try again.',
      'auth_err_email_unverified':
          'Your email is not verified. Enter the code sent to your inbox.',
      'auth_verify_title': 'Verify Your Email',
      'auth_verify_desc': 'Enter the 6-digit code sent to {}.',
      'auth_verify_btn': 'Verify & Sign In',
      'auth_verify_resend': 'Resend Code',
      'auth_verify_resent': 'Code sent.',
      'auth_err_reset_pass_failed':
          'Failed to reset password. Please try again.',
      'auth_err_generic': 'An error occurred.',
      'auth_err_rate_limited': 'Too many requests. Please try again later.',
      'sync_login_hint':
          'Please sign in at the top of the profile to enable Cloud Backup.',
      'profile_guest': 'Guest User',
      'profile_not_logged_in': 'Cloud sync is not active',
      'profile_watchlist': 'Watchlist',
      'profile_stats': 'Stats',
      'profile_history': 'History',
      'profile_genres': 'Favorite Genres',
      'profile_total': 'Total',
      'profile_berbat': 'Awful',
      'profile_eh': 'Meh',
      'profile_iyi': 'Good',
      'profile_harika': 'Amazing',
      'profile_empty_watchlist':
          'You haven\'t added anything to your watchlist.',
      'profile_empty_history': 'You haven\'t rated anything yet.',
      'profile_no_genres': 'No preference signals yet.',
      'profile_rated_movies': 'Last Rated Items',
      'profile_clear_confirm': 'Clear all data',
      'profile_family_mode': 'Family Friendly Mode (PG-13)',
      'settings_title': 'Settings & Preferences',
      'lang_ko': 'Korean Cinema',
      'lang_eu': 'European Cinema',
      'lang_en': 'Hollywood',
      'lang_tr': 'Turkish Cinema',
      'lang_ja': 'Japanese Cinema',
      'lang_hi': 'Bollywood',
      'lang_fa': 'Iranian Cinema',
      'lang_all': 'All',
      'lang_unknown': 'Unknown',
      'auth_register_subtitle':
          'Create your account, keep your taste profile with you on all devices.',
      'auth_login_subtitle':
          'Sign in to your account, continue from where you left off.',
      'auth_display_name_optional': 'Display Name (optional)',
      'auth_email_label': 'Email',
      'auth_password_label': 'Password',
      'profile_account': 'Account',
      'detail_where_to_watch': 'WHERE TO WATCH?',
      'detail_keywords': 'KEYWORDS',
      'detail_storyline': 'STORYLINE',
      'detail_collection': 'COLLECTION',
      'detail_rate_title': 'RATE THIS TITLE',
      'detail_your_review': 'YOUR REVIEW',

      // Review
      'review_spoiler': 'Contains Spoiler',
      'review_private': 'Private Rating',
      'review_save': 'Save Review',
      'review_friends_title': 'Friends\' Reviews',
      'review_community_title': 'Community Reviews',
      'review_empty_first': 'Leave the first review',
      'review_no_friends': 'No reviews from friends yet',
      'review_comment_hint': 'Share your thoughts about this movie...',
      'review_spoiler_warning': 'Contains spoiler. Tap to view.',
      'review_report': 'Report review',
      'review_report_title': 'Why are you reporting this review?',
      'review_report_profanity': 'Profanity / hate speech',
      'review_report_spam': 'Spam / advertising',
      'review_report_spoiler': 'Unmarked spoiler',
      'review_report_harassment': 'Harassment',
      'review_report_other': 'Other',
      'review_reported': 'Report received. Thank you.',
      'review_longpress_hint': 'Press and hold a review to report or block',
      'review_block_user': 'Block user',
      'review_block_confirm_title': 'Block this user?',
      'review_block_confirm_msg':
          'You will no longer see their reviews or activity, and any friendship will be removed.',
      'review_blocked': 'User blocked',
      'blocked_users_title': 'Blocked Users',
      'blocked_users_subtitle':
          'People whose reviews and activity you have hidden',
      'blocked_users_empty': 'You have not blocked anyone.',
      'blocked_users_unblock': 'Unblock',
      'blocked_users_unblock_confirm_title': 'Remove block?',
      'blocked_users_unblock_confirm_msg':
          '{} will be unblocked and their reviews may appear again.',
      'blocked_users_unblocked': 'User unblocked',
      'blocked_users_load_error': 'Could not load blocked users.',
      'review_delete': 'Delete review',
      'review_delete_confirm': 'Delete this review? Your rating will be kept.',
      'review_deleted': 'Review deleted',
      'rating_delete_with_comment_title': 'Remove rating?',
      'rating_delete_with_comment_msg':
          'Removing this rating will also delete your review.',
      'my_reviews_title': 'My Reviews',
      'my_reviews_empty': 'You haven\'t written any reviews yet.',
      'my_reviews_subtitle': 'All reviews you\'ve written, in one place',
      'block': 'Block',
      'score_votes': '{} votes',
      'score_community_a11y': '{}% of cinema+ members liked it',

      // Match
      'match_title': 'Match with Friend',
      'match_desc':
          'Decide what to watch together by sharing a room code or joining a room.',
      'match_create_room': 'Create Room',
      'match_join_room': 'Join Room',
      'match_enter_code': 'Enter Room Code',
      'match_invalid_code': 'Invalid room code.',
      'match_room_code': 'Room Code:',
      'match_waiting': 'Waiting for the other user to join...',
      'match_start': 'Start Match',
      'match_found': 'IT\'S A MATCH!',
      'match_found_desc': 'The content you both liked:',
      'match_go_back': 'Go Back',
      'match_loading': 'Loading...',
      'match_swipe_left': 'Skip',
      'match_swipe_right': 'Like',
      'match_swiping_title': 'Match Swiping',
      'match_connecting': 'Connecting...',
      'match_status': 'Match Status',

      // Swipe
      'swipe_title': 'Rate',
      'swipe_left_desc': 'Swipe left to skip',
      'swipe_right_desc': 'Swipe right to like',
      'swipe_empty':
          'No more content to rate. Try changing your favorites or check back later!',
      'swipe_hint': 'Swipe cards',

      // Browse
      'browse_title': 'Browse',
      'browse_retry': 'Retry',
      'browse_random': 'Surprise Me',
      'browse_mood': 'By Mood',
      'browse_trending': 'Trending',
      'browse_popular': 'Popular',
      'browse_top_rated': 'Top Rated',
      'browse_error': 'An error occurred while loading content.',
      'browse_conn_error': 'Check your internet connection and try again.',
      'browse_api_missing': 'Configuration Error',
      'browse_api_missing_desc':
          'Server-side service configuration error. Please try again later.',
      'browse_refresh': 'Refresh',
      'browse_movies': 'Movies',
      'browse_tvs': 'TV Shows',

      // Moods
      'mood_funny': 'Make me laugh',
      'mood_thrill': 'Need thrillers',
      'mood_cry': 'Make me cry',
      'mood_action': 'Action pack',
      'mood_light': 'Light & cozy',
      'mood_thought': 'Thought provoking',
      'mood_romance': 'Romantic evening',
      'mood_classic': '90\'s classic',
      'mood_scary': 'Scary night',
      'mood_doc': 'Documentary',
      'mood_fantasy': 'Fantasy world',
      'mood_crime': 'Crime & mystery',

      // Search
      'search_title': 'Search',
      'search_hint': 'Search movies or TV shows...',
      'search_empty': 'Search history is empty.',
      'search_history': 'Search History',
      'search_clear': 'Clear',
      'search_no_results': 'No results found.',

      // Movie Detail
      'detail_director': 'Director',
      'detail_directors': 'Directors',
      'detail_cast': 'Cast',
      'detail_reviews': 'Reviews',
      'detail_watchlist_add': 'Add to Watchlist',
      'detail_watchlist_remove': 'Remove from Watchlist',
      'detail_rating': 'Rating',
      'detail_runtime': 'Runtime',
      'detail_seasons': 'Seasons',
      'detail_no_reviews': 'No reviews yet.',
      'detail_similar': 'Similar Content',
      'detail_minutes': 'min',
      'detail_seasons_count': 'seasons',
      'detail_episodes_count': 'episodes',

      // Added / Missing
      'search_quick_search': 'Quick Search',
      'search_trending_movies': 'Trending Movies',
      'search_failed': 'Search failed.',
      'browse_popular_movies': 'Popular Movies',
      'browse_popular_tvs': 'Popular TV Shows',
      'browse_top_rated_movies': 'Top Rated',
      'browse_now_playing_theaters': 'In Theaters',
      'browse_airing_today_tv': 'Airing Today',
      'browse_on_the_air_tv': 'On The Air',
      'browse_upcoming_coming': 'Coming Soon',
      'browse_for_you_personal': 'For You',
      'tonight_title': 'What to Watch Tonight?',
      'tonight_shuffle': 'Show another',
      'tonight_not_interested': 'Not interested',
      'dna_title': 'Your Cinema DNA',
      'dna_banner_desc': 'Discover the identity of your taste.',
      'dna_analyzing': 'Analyzing your taste…',
      'dna_error': "Couldn't build your DNA",
      'dna_not_ready': 'Your DNA is still forming',
      'dna_not_ready_desc':
          'Rate a few more titles and your taste identity will emerge.',
      'dna_you_are': 'You are',
      'dna_themes': 'Your recurring themes',
      'dna_top_genres': 'Your top genres',
      'dna_signals': 'Your taste signature',
      'dna_share': 'Share',
      'dna_share_button': 'Share your DNA',
      'dna_arch_dark_chronicler': 'The Dark Chronicler',
      'dna_arch_emotion_seeker': 'The Emotion Seeker',
      'dna_arch_world_builder': 'The World Explorer',
      'dna_arch_adrenaline_junkie': 'The Adrenaline Seeker',
      'dna_arch_joy_chaser': 'The Joy Chaser',
      'dna_arch_truth_seeker': 'The Truth Seeker',
      'dna_arch_eternal_child': 'The Eternal Child',
      'dna_arch_genre_nomad': 'The Genre Nomad',
      'dna_ess_dark_chronicler':
          'You are drawn to shadows, tension and moral grey.',
      'dna_ess_emotion_seeker':
          'You chase stories that touch the heart and reveal people.',
      'dna_ess_world_builder':
          'New universes and impossible worlds call to you.',
      'dna_ess_adrenaline_junkie': 'Pace, action and adventure are your fuel.',
      'dna_ess_joy_chaser': 'Laughter and lightness are your refuge.',
      'dna_ess_truth_seeker':
          'True stories and the lessons of the past intrigue you.',
      'dna_ess_eternal_child':
          'The child in you never grew up — and that rules.',
      'dna_ess_genre_nomad': "You don't fit one genre; you taste every color.",
      'dna_ess_sec_dark_chronicler':
          'Shadows, suspense and moral ambiguity also feed your taste.',
      'dna_ess_sec_emotion_seeker':
          'Emotional depth and human stories also captivate you.',
      'dna_ess_sec_world_builder':
          'Extraordinary universes and highly imaginative worlds also draw your interest.',
      'dna_ess_sec_adrenaline_junkie':
          'Pace, action and adventure are also sources of excitement for you.',
      'dna_ess_sec_joy_chaser':
          'Lightness, joy and comedy are also among your safe havens.',
      'dna_ess_sec_truth_seeker':
          'True stories and real-life experiences are also on your radar.',
      'dna_ess_sec_eternal_child':
          'The child in you that never grows up also finds its place in stories.',
      'dna_ess_sec_genre_nomad':
          'Colors of different genres also show themselves in your taste.',
      'dna_era_modern': "A modern soul — {p} of your loves are post-2015.",
      'dna_era_classic': 'A classic soul — you chase the magic of old cinema.',
      'dna_era_traveler': 'A time traveler — you feel at home in every era.',
      'dna_depth_deep':
          'A deep-cut hunter — you find the gems the crowd skips.',
      'dna_depth_zeit':
          "A zeitgeist rider — you keep your finger on the pulse.",
      'dna_depth_balanced':
          'A balanced explorer — you love both blockbusters and hidden gems.',
      'dna_critic_tough':
          'A tough critic — only {p} of your ratings are "Great".',
      'dna_critic_generous':
          'A generous heart — you\'re never afraid to call it "Great".',
      'dna_critic_balanced':
          'A measured critic — your praise and your criticism both land.',
      'dna_blind': "Your blind spot: {g} — it just doesn't reach you.",
      'dna_shift': 'Your taste has drifted from {from} to {to}.',
      'dna_accuracy':
          'Taste match rate in recent recommendations: {p} — across {n} picks.',
      'dna_share_header': 'My Cinema DNA: {a}',
      'dna_share_themes': 'My themes',
      'dna_share_cta': 'See your DNA',
      'dna_share_cta_none': 'Discover your own Cinema DNA!',
      'tonight_match': 'match',
      'reco_reason_seed': 'Because you liked {x}',
      'reco_reason_friend': '{x} loved this',
      'browse_trending_week': 'Trending This Week',
      'browse_api_unauthorized_desc':
          'The server is unable to authenticate with the movie service. Please contact support.',
      'browse_offline_title': 'You are Offline',
      'browse_offline_desc':
          'Please check your internet connection and try again.',
      'browse_surprise': 'Surprise me',
      'swipe_rate': 'Rate',
      'swipe_not_watched': 'Not Watched',
      'swipe_liked': 'Liked',
      'swipe_disliked': 'Disliked',
      'swipe_failed': 'Connection failed.',
      'detail_trailer': 'Trailer',
      'detail_watchlist_add_short': 'Watchlist',
      'detail_share_text':
          'Check out this recommendation from What to Watch: {}',
      'detail_season_label': 'Season {}',
      'recommend_pick_friend': 'Who should we recommend it to?',
      'recommend_note_hint': 'Add a note (optional)',
      'recommend_sent': 'Recommendation sent!',
      'recommend_need_login': 'Sign in to send recommendations.',
      'recommend_no_friends': 'Add friends from the Social tab first.',
      'match_button': 'Match',
      'profile_rating': 'Rating',
      'semantics_refresh': 'Refresh recommendations',
      'semantics_go_back': 'Go back',
      'semantics_remove_watchlist': 'Remove from watchlist',
      'semantics_close': 'Close',
      'semantics_reset': 'Reset selections',
      'results_title': 'Recommendations',
      'theme_switch': 'Switch theme',
      'search_trending_shows': 'Trending TV Shows',
      'search_new_releases': 'New Releases',
      'semantics_undo': 'Undo rating',
      'match_together': 'Together',
      'match_switch_match': 'Switch to Match',
      'match_together_desc':
          'Both choose genres, we\'ll find common suggestions',
      'match_single_desc': 'Enter a title you like, we\'ll find similar ones',
      'match_search_placeholder': 'Search a movie or TV show',
      'match_empty_title': 'Find similar titles to what you love instantly',
      'match_no_similar': 'No similar content found',
      'match_you': 'You',
      'match_friend': 'Friend',
      'match_find_suggestions': 'Find Common Suggestions',
      'match_select_at_least_one': 'Both choose at least 1 genre',
      'match_genres_count': '{} genres',
      'match_similar_to': 'Similar to "{}"',
      'watchlist_empty_title': 'List is empty',
      'watchlist_empty_desc':
          'Tap the "Watchlist" button\non a movie or TV show detail screen',
      'swipe_ratings_count': '{} ratings',
      'watchlist_items': 'items',
      'onboarding_subtitle_movie_genres':
          'Select a few genres that interest you to get started',
      'onboarding_subtitle_tv_genres': 'Select your interests to continue',
      'onboarding_search_hint_movie': 'Search movie...',
      'onboarding_search_hint_tv': 'Search TV show...',
      'onboarding_search_empty_movie':
          'Search by movie name\nto add your favorites',
      'onboarding_search_empty_tv':
          'Search by TV show name\nto add your favorites',
      'browse_friends_activity': 'Recent Activity from Friends',
      'browse_rating_good': 'liked it',
      'browse_rating_excellent': 'loved it',
      'recap_journey_title': 'Your {}\nCinema Journey',
      'recap_journey_desc':
          'We compiled all your ratings from the past year. Swipe to discover your recap!',
      'recap_swipe_continue': 'Swipe to continue',
      'recap_what_watched': 'What Did You Watch?',
      'recap_total_titles': '{} Titles',
      'recap_rated_sub': 'rated and reviewed!',
      'recap_stat_amazing': 'Amazing 🌟',
      'recap_stat_good': 'Good 👍',
      'recap_stat_meh': 'Meh 😐',
      'recap_stat_awful': 'Awful 👎',
      'recap_top_genres': 'YOUR TOP GENRES',
      'recap_no_taste_data': 'Not enough taste data yet.',
      'recap_highest_rated': 'YOUR HIGHEST RATED TITLES',
      'recap_rated_amazing': 'Rated as Amazing',
      'recap_no_amazing_yet': "You haven't rated any title \"Amazing\" yet.",
      'recap_share_title': 'MY {} CINEMA JOURNEY',
      'recap_share_sub': 'rated {} titles',
      'recap_share_genres': 'My Favorite Genres:',
      'recap_share_button': 'Share Your Recap',
      'what_to': 'what to ',
      'watch': 'watch?',
      'personalize_recommendations': 'Personalize Recommendations',
      'complete_the_2minute_survey_fo':
          'Complete the 2-minute survey for the best matching movies and shows!',
      'you_are_offline_your_changes_w':
          'You are offline — Your changes will be synced',
      'no_common_genres': 'No Common Genres',
      'you_have_no_common_genres_sele':
          'You have no common genres selected. Please select at least one genre in common to find a joint recommendation.',
      'movie_match': 'Movie Match',
      'movie_match_alt': 'Movie Match',
      'with_friend': 'With Friend',
      'movie_matcher': 'Movie Matcher',
      'search_for_a_movie_or_tv_show_':
          'Search for a movie or TV show you like, we\'ll analyze its similarities to recommend matching titles.',
      'couch_mode_matcher': 'Couch Mode Matcher',
      'pass_the_phone_to_the_person_n':
          'Pass the phone to the person next to you. Both select your favorite genres, and we\'ll discover matches you\'ll both enjoy.',
      'player_1_you_select_your_favor':
          '👉 Player 1 (You): Select your favorite genres...',
      'player_2_friend_now_its_your_t':
          '👉 Player 2 (Friend): Now it\'s your turn...',
      'common_match': 'Common Match',
      'authentication_required': 'Authentication Required',
      'please_sign_in_to_view_watchli':
          'Please sign in to view watchlist intersections with your friends.',
      'no_friends_yet': 'No Friends Yet',
      'you_must_add_friends_first_to_':
          'You must add friends first to match with them.',
      'add_manage_friends': 'Add / Manage Friends',
      'online_friend_match': 'Online Friend Match',
      'select_a_friend_to_find_common':
          'Select a friend to find common titles in your watchlists and get joint recommendations based on your shared interests.',
      'select_a_friend_to_match_with': 'Select a friend to match with:',
      'manage': 'Manage',
      'no_common_movies': 'No Common Movies',
      'neither_of_you_have_added_the_':
          'Neither of you have added the same movies to your watchlists.',
      'find_joint_recommendations': 'Find Joint Recommendations',
      'hide_title': 'Hide Title',
      'are_you_sure_you_want_to_block':
          'Are you sure you want to block this title and permanently hide it from all lists?',
      'title_hidden_and_removed_from_': 'Title hidden and removed from lists.',
      'hide': 'Hide',
      'undo': 'Undo',
      'block_and_hide_title': 'Block and Hide Title',
      'recommend_to_friend': 'Recommend to Friend',
      'match_details': 'Match Details',
      'personal_taste_match': 'Personal Taste Match',
      'tmdb_rating': 'TMDB Rating',
      'cinema_member_score': 'cinema+ Member Score',
      'review_saved_successfully': 'Review saved successfully',
      'saved': 'Saved ✔',
      'filmography': 'FILMOGRAPHY',
      'do_you_want_to_delete_this_rat':
          'Do you want to delete this rating and remove it from your history?',
      'delete': 'Delete',
      'your_cinema_recap': 'Your Cinema Recap!',
      'discover_your_cinema_journey_o':
          'Discover your cinema journey of the year.',
      'see_taste_matches_manage_reque':
          'See taste matches, manage requests and activity feeds.',
      'see_all': 'See All',
      'filters_out_deadpool_euphoria_':
          'Filters out Deadpool, Euphoria, and mature R-rated content.',
      'active': ' (Active)',
      'filter': 'Filter',
      'year': 'Year',
      'language': 'LANGUAGE',
      'try_different_filters': 'Try different filters',
      'advanced_filters': 'Advanced Filters',
      'country_region': 'COUNTRY / REGION',
      'platform': 'PLATFORM',
      'minimum_tmdb_score': 'MINIMUM TMDB SCORE',
      'filter_and_list': 'Filter and List',
      'please_enter_a_username': 'Please enter a username.',
      'profile_updated_successfully': 'Profile updated successfully.',
      'friend_request_sent':
          'Friend request sent. You will become friends once they accept.',
      'friend_request_accepted': 'Friend request accepted. You are now friends.',
      'friend_request_declined': 'Request declined.',
      'friend_request_withdrawn': 'Request withdrawn.',
      'friend_removed': 'Friend removed.',
      'social_network': 'Social Network',
      'requests': 'Requests',
      'activity': 'Activity',
      'top_lists': 'Popular',
      'top_lists_title': 'Popular Lists',
      'top_lists_empty':
          'No public profiles yet. Share your profile to get things rolling!',
      'top_lists_likes': 'likes',
      'top_lists_you': 'You',
      'top_lists_view_profile': 'View list',
      'customize_profile': 'Customize Profile',
      'username_username': 'Username (@username)',
      'public_profile': 'Public Profile',
      'when_disabled_your_profile_can':
          'When disabled, your profile cannot be viewed on the web.',
      'save_settings': 'Save Settings',
      'username_or_email': 'Username or email...',
      'no_friends_added_yet': 'No friends added yet.',
      'remove_friend': 'Remove Friend',
      'remove': 'Remove',
      'no_pending_requests': 'No pending requests.',
      'received_requests': 'Received Requests',
      'sent_requests': 'Sent Requests',
      'pending': 'Pending',
      'no_friend_activity_yet': 'No friend activity yet.',
      'recommended_to_you': 'Recommended to You',
      'cinema_taste_match': 'Cinema Taste Match',
      'no_activity_from_this_friend_y': 'No activity from this friend yet.',
      'error_saving_rating': 'Error saving rating.',
      'error_undoing_rating': 'Error undoing rating.',
      'content_filters': 'Content Filters',
      'language_region': 'LANGUAGE / REGION',
      'streaming_platforms': 'STREAMING PLATFORMS',
      'all': '🎬 All',
      'no_more_content': 'No More Content',
      'loading_more': 'Loading more...',
      'no_more_content_matches_your_f':
          'No more content matches your filters.\nYou can clear the filters to continue.',
      'discovery_gestures': 'Discovery Gestures',
      'swipe_cards_to_train_our_recom':
          'Swipe cards to train our recommendation engine!',
      'swipe_right': 'Swipe Right',
      'liked_good_or_amazing': 'Liked (Good or Amazing)',
      'swipe_left': 'Swipe Left',
      'disliked_meh_or_awful': 'Disliked (Meh or Awful)',
      'tap_card': 'Tap Card',
      'view_details_trailer_cast': 'View Details, Trailer & Cast',
      'got_it_lets_start': 'Got it, Let\'s Start!',
      'an_error_occurred_while_loadin': 'An error occurred while loading.',
      'remove_from_watchlist': 'Remove from watchlist?',
      'your_common_watchlist_intersec': 'Your Common Watchlist ({} Titles)',
      'title_removed_from_watchlist': '{} removed from watchlist.',
      'synergy_score_match': '{}% Match',
      'error_occurred_msg': 'Error: {}',
      'share_profile_text':
          'Follow me on What to Watch! Check out my watchlist and favorites here: {}',
      'profile_share': 'Share',
      'profile_share_message':
          'Follow me on What to Watch! Check out my watchlist and favorites here: {}',
      'profile_share_no_username':
          'Set a username in your profile to share your web profile.',
      'taste_score_match': '{}% match',
      'remove_friend_confirm_msg':
          'Are you sure you want to remove {} from friends?',
      'recommended_by_user': 'Recommended by {}',
      'friend_taste_match_desc':
          'You have a {}% movie taste match with this friend.',
      'active_count_label': ' ({} Active)',
      'sync_retry': 'Retry',
      'retry': 'Try again',
      'splash_tagline': ' | What to Watch?',
      'web_profile': 'Web Profile',
      'social_customize_desc':
          'Choose a username to add friends and see your cinema harmony.',
      'social_set_username': 'Set Username',
      'browse_surprise_title': 'Lucky Pick 🎲',
      'browse_surprise_desc':
          'This dice button selects a random movie tailored to your tastes based on the films you have rated. Use it whenever you want to be surprised!',
      'recap_share_template':
          '🎬 My {year} Cinema Recap on Ne İzlesem!\n\nI rated {total} movies & shows this year! 🍿\nMy Top Genres:\n{genres}\n\n{link_section}\n#NeIzlesem #Wrapped{year}',
      'recap_share_link_yes': 'Check out my profile: {url}',
      'recap_share_link_no': 'Rate your titles and see your recap!',
      'change_language': 'Change Language',
      'got_it': 'Got it',
    },
    'tr': {
      'app_title': 'Cinema+',
      'tagline': 'NE İZLESEM?',
      'profile_about': 'Uygulama Hakkında',
      'profile_about_desc': 'Sürüm, yazar ve uygulama bilgileri',
      'profile_about_title': 'Cinema+ | Ne İzlesem? Hakkında',
      'profile_about_content':
          'Cinema+, Tinder tarzı kaydırma arayüzü ile film ve dizi keşfetmenizi, arkadaşlarınızla ortak zevklerinizi eşleştirmenizi ve benzersiz Sinema DNA\'nızı oluşturmanızı sağlayan kişisel sinema asistanınızdır.',
      'profile_about_author': 'Yazar',
      'profile_about_version': 'Sürüm',
      'tmdb_attribution':
          'Bu ürün TMDB API\'sini kullanır ancak TMDB tarafından onaylanmış veya sertifikalandırılmış değildir.',
      'tab_browse': 'Keşfet',
      'tab_swipe': 'Değerlendir',
      'tab_match': 'Eşleştir',
      'tab_together': 'Birlikte',
      'together_match': 'Eşleştir',
      'together_friends': 'Arkadaşlar',
      'together_desc': 'Arkadaşlarınla keşfet, eşleş ve paylaş.',
      'together_social_title': 'Sosyal & Arkadaşlar',
      'together_social_desc': 'Arkadaşlar, istekler ve aktivite akışı',
      'together_friend_match_title': 'Arkadaşımla Eşleş',
      'together_friend_match_desc': 'Ortak beğeniler ve öneriler',
      'together_couch_title': 'Aynı Cihazda',
      'together_couch_desc': 'Tek telefonda',
      'together_similar_title': 'Benzer Film Bul',
      'together_similar_desc': 'Sevdiğin bir filme benzer yapımları keşfet',
      'tab_search': 'Ara',
      'tab_profile': 'Profil',

      // Global üst bar & menü
      'menu_social': 'Sosyal',
      'menu_preferences': 'Tercihler',
      'menu_account': 'Hesap',
      'menu_my_friends': 'Arkadaşlarım',
      'menu_requests': 'Arkadaşlık İstekleri',
      'menu_activity': 'Aktivite Akışı',
      'menu_top_lists': 'Top Listeler',
      'menu_my_profile': 'Profilim',
      'theme_dark': 'Koyu',
      'theme_light': 'Açık',

      // Kütüphane (showroom)
      'library_title': 'Kütüphanen',
      'profile_cinema_identity': 'Sinema Kimliğin',
      'danger_zone': 'Tehlike Bölgesi',
      'sort_added': 'Eklenme',
      'sort_rating': 'Puan',
      'sort_year': 'Yıl',
      'sort_my_rating': 'Puanım',
      'library_rated_empty_title': 'Henüz değerlendirme yok',
      'library_rated_empty_desc':
          'Film ve dizileri puanladıkça geçmişin burada birikir.',

      // Onboarding
      'onboarding_loading': 'Hazırlanıyor...',
      'onboarding_quick_rating': 'Hızlı değerlendirme',
      'onboarding_skip': 'Atla',
      'onboarding_not_watched': 'İzlemedim',
      'onboarding_title_movie_genres': 'Hangi tür filmleri seversiniz?',
      'onboarding_title_tv_genres': 'Hangi tür dizileri seversiniz?',
      'onboarding_title_fav_movies': 'En sevdiğiniz 3 filmi seçin',
      'onboarding_title_fav_tvs': 'En sevdiğiniz 3 diziyi seçin',
      'onboarding_title_rating': 'Hızlı Değerlendirme',
      'onboarding_search_hint': 'Ara...',
      'onboarding_fav_desc':
          'İsteğe bağlı — en fazla 3 adet favorinizi ekleyebilirsiniz.',
      'onboarding_next': 'Devam',
      'onboarding_finish': 'Başla',
      'onboarding_selected': 'seçildi',
      'onboarding_movie': 'Film',
      'onboarding_tv': 'Dizi',
      'onboarding_done': 'Tamam',
      'swipe_recommended': 'Sana Özel',

      // Profile
      'profile_reset_title': 'Tüm Verileri Sıfırla',
      'profile_reset_content':
          'Değerlendirmeleriniz, yorumlarınız, izleme listeniz, tercihleriniz ve bulut yedekleriniz kalıcı olarak sıfırlanacak ve oturumunuz kapatılacaktır. Devam etmek istiyor musunuz?',
      'profile_cancel': 'Vazgeç',
      'profile_reset': 'Sıfırla',
      'profile_reset_failed_title': 'Sıfırlama Başarısız',
      'profile_reset_failed_content':
          'Sunucu verileri silinemedi. Lütfen internet bağlantınızı kontrol edip tekrar deneyin.',
      'ok': 'Tamam',
      'auth_title_login': 'Giriş Yap',
      'auth_title_register': 'Kayıt Ol',
      'auth_email': 'E-posta Adresi',
      'auth_password': 'Şifre',
      'auth_display_name': 'Görüntülenecek Ad',
      'auth_button_login': 'Giriş Yap',
      'auth_or': 'veya',
      'auth_google_button': 'Google ile devam et',
      'auth_button_register': 'Kayıt Ol',
      'auth_toggle_to_register': 'Hesabınız yok mu? Kayıt Olun',
      'auth_toggle_to_login': 'Zaten hesabınız var mı? Giriş Yapın',
      'sync_title': 'Bulut Yedekleme',
      'sync_desc':
          'İzleme listenizi, puanlarınızı ve geçmişinizi güvenle bulutta saklayın.',
      'sync_now': 'Şimdi Eşitle',
      'sync_success': 'Başarıyla senkronize edildi',
      'sync_last': 'Son eşitleme: ',
      'auth_logout': 'Çıkış Yap',
      'auth_logout_confirm':
          'Hesabınızdan çıkış yapmak istiyor musunuz? Puanlarınız ve listeleriniz bu cihazda kalır.',
      'auth_logout_wipe_local': 'Bu cihazdaki verileri de sil',
      'session_expired_message':
          'Oturumunuz sona erdi. Verileriniz bu cihazda güvende. Tekrar giriş yapın.',
      'auth_conflict_title': 'Hesap Çakışması',
      'auth_conflict_desc':
          'Bu cihazda, giriş yaptığınız hesaba henüz bağlı olmayan yerel veriler (puanlar, listeler) var — misafir olarak ya da başka bir hesapla oluşturulmuş olabilir. "Cihazdakileri Sil" seçeneği bu verileri cihazdan kalıcı olarak siler. Nasıl devam etmek istersiniz?',
      'auth_conflict_merge': 'Bu Hesapla Birleştir',
      'auth_conflict_delete': 'Cihazdakileri Sil & Buluttan Yükle',
      'auth_conflict_cancel': 'Girişi İptal Et',
      'auth_delete_account': 'Hesabı Sil',
      'auth_delete_confirm':
          'Bu işlem hesabınızı ve tüm bulut verilerinizi kalıcı olarak silecektir. Emin misiniz?',
      'auth_delete_ack': 'Bu işlemin geri alınamayacağını anlıyorum.',
      'auth_delete_done':
          'Hesabınız ve bulut verileriniz kalıcı olarak silindi.',
      'auth_forgot_password_link': 'Şifremi Unuttum',
      'auth_forgot_title': 'Şifremi Unuttum',
      'change_password_title': 'Şifre Değiştir',
      'change_password_desc':
          'Şifreniz değiştirildiğinde tüm cihazlarınızdan çıkış yapılacaktır.',
      'change_password_old_password': 'Mevcut Şifre',
      'change_password_new_password': 'Yeni Şifre',
      'change_password_confirm_password': 'Yeni Şifreyi Onayla',
      'change_password_button': 'Şifreyi Güncelle',
      'change_password_error_mismatch': 'Yeni şifreler eşleşmiyor.',
      'change_password_error_short': 'Yeni şifre en az 6 karakter olmalıdır.',
      'change_password_success': 'Şifreniz başarıyla değiştirildi.',
      'google_unlink_title': 'Google Bağlantısını Kaldır',
      'google_unlink_desc': 'Devam etmek için hesap parolanızı girin.',
      'google_unlink_button': 'Bağlantıyı Kaldır',
      'google_unlink_success': 'Google hesabı bağlantısı kaldırıldı.',
      'auth_err_google_unlink_failed': 'Google bağlantısı kaldırılamadı.',
      'auth_forgot_email_desc':
          'Şifre sıfırlama kodunu almak için kayıtlı e-posta adresinizi girin.',
      'auth_forgot_code_title': 'Kodu Doğrula',
      'auth_forgot_code_desc':
          'E-postanıza gönderilen 6 haneli doğrulama kodunu girin.',
      'auth_forgot_reset_title': 'Şifreyi Sıfırla',
      'auth_forgot_reset_desc':
          'Hesabınız için en az 8 karakterli yeni bir şifre belirleyin.',
      'auth_forgot_label_code': '6 Haneli Doğrulama Kodu',
      'auth_forgot_label_new_pass': 'Yeni Şifre',
      'auth_forgot_btn_send_code': 'Kod Gönder',
      'auth_forgot_btn_verify': 'Kodu Doğrula',
      'auth_forgot_btn_reset': 'Şifreyi Güncelle',
      'auth_forgot_btn_back': 'Geri Dön',
      'auth_forgot_err_name_empty': 'Ad alanı boş bırakılamaz.',
      'auth_forgot_err_email_invalid': 'Geçerli bir e-posta girin.',
      'auth_forgot_err_code_length': '6 haneli kodu eksiksiz girin.',
      'auth_forgot_err_pass_length': 'Parola en az 8 karakter olmalıdır.',
      'auth_forgot_success_reset':
          'Şifreniz başarıyla sıfırlandı. Yeni şifrenizle giriş yapabilirsiniz.',
      'auth_err_google_not_configured':
          'Google girişi bu derlemede yapılandırılmamış.',
      'auth_err_google_token_failed': 'Google ID token alınamadı.',
      'auth_err_google_failed':
          'Google ile giriş yapılamadı. Lütfen tekrar deneyin.',
      'auth_err_register_failed':
          'Kayıt yapılamadı. Lütfen bağlantınızı kontrol edin.',
      'auth_err_login_failed':
          'Giriş yapılamadı. Lütfen bağlantınızı kontrol edin.',
      'auth_err_delete_failed': 'Hesap silinemedi. Lütfen tekrar deneyin.',
      'auth_err_change_pass_failed':
          'Parola değiştirilemedi. Lütfen tekrar deneyin.',
      'auth_err_email_exists': 'Bu e-posta zaten kayıtlı.',
      'auth_err_invalid_credentials': 'E-posta veya parola hatalı.',
      'auth_err_wrong_password': 'Mevcut parola hatalı.',
      'auth_err_user_not_found': 'Kullanıcı bulunamadı.',
      'auth_err_forgot_send_failed':
          'Sıfırlama kodu gönderilemedi. Lütfen bağlantınızı kontrol edin.',
      'auth_err_verify_code_failed':
          'Doğrulama kodu geçersiz. Lütfen tekrar deneyin.',
      'auth_err_email_unverified':
          'E-posta adresin doğrulanmamış. Gelen kutundaki kodu gir.',
      'auth_verify_title': 'E-postanı Doğrula',
      'auth_verify_desc': '{} adresine gönderilen 6 haneli kodu gir.',
      'auth_verify_btn': 'Doğrula ve Giriş Yap',
      'auth_verify_resend': 'Kodu Tekrar Gönder',
      'auth_verify_resent': 'Kod gönderildi.',
      'auth_err_reset_pass_failed':
          'Şifre sıfırlanamadı. Lütfen tekrar deneyin.',
      'auth_err_generic': 'Bir hata oluştu.',
      'auth_err_rate_limited':
          'Çok fazla istek. Lütfen biraz sonra tekrar deneyin.',
      'sync_login_hint':
          'Bulut yedeklemeyi etkinleştirmek için lütfen profil sayfasının üst kısmından giriş yapın.',
      'profile_guest': 'Misafir Kullanıcı',
      'profile_not_logged_in': 'Bulut eşitleme aktif değil',
      'profile_watchlist': 'İzleme Listesi',
      'profile_stats': 'İstatistikler',
      'profile_history': 'Geçmiş',
      'profile_genres': 'En Sevdiğin Türler',
      'profile_total': 'Toplam',
      'profile_berbat': 'Berbat',
      'profile_eh': 'Eh',
      'profile_iyi': 'İyi',
      'profile_harika': 'Harika',
      'profile_empty_watchlist': 'Henüz film veya dizi eklemediniz.',
      'profile_empty_history': 'Henüz değerlendirme yapmadınız.',
      'profile_no_genres': 'Tercih bulunamadı.',
      'profile_rated_movies': 'Son Değerlendirilenler',
      'profile_clear_confirm': 'Tüm verileri temizle',
      'profile_family_mode': 'Aile Dostu Mod (PG-13)',
      'settings_title': 'Ayarlar & Tercihler',
      'lang_ko': 'Kore Sineması',
      'lang_eu': 'Avrupa Sineması',
      'lang_en': 'Hollywood',
      'lang_tr': 'Türk Sineması',
      'lang_ja': 'Japon Sineması',
      'lang_hi': 'Bollywood (Hint)',
      'lang_fa': 'İran Sineması',
      'lang_all': 'Tümü',
      'lang_unknown': 'Bilinmeyen',
      'auth_register_subtitle':
          'Hesabını oluştur, zevk profilin her cihazda seninle olsun.',
      'auth_login_subtitle': 'Hesabına gir, kaldığın yerden devam et.',
      'auth_display_name_optional': 'Ad (isteğe bağlı)',
      'auth_email_label': 'E-posta',
      'auth_password_label': 'Parola',
      'profile_account': 'Hesap',
      'detail_where_to_watch': 'NEREDE İZLENİR?',
      'detail_keywords': 'ANAHTAR KELİMELER',
      'detail_storyline': 'KONU',
      'detail_collection': 'SERİNİN DİĞER FİLMLERİ',
      'detail_rate_title': 'BU YAPIMI PUANLA',
      'detail_your_review': 'YORUMUNUZ',

      // Review
      'review_spoiler': 'Spoiler İçerir',
      'review_private': 'Gizli Puan/Yorum',
      'review_save': 'Yorumu Kaydet',
      'review_friends_title': 'Arkadaşlarından Yorumlar',
      'review_community_title': 'Topluluk Yorumları',
      'review_empty_first': 'İlk yorumu sen bırak',
      'review_no_friends': 'Arkadaşlarından henüz yorum yok',
      'review_comment_hint': 'Bu yapım hakkındaki düşüncelerini paylaş...',
      'review_spoiler_warning': 'Spoiler içeriyor. Görmek için dokunun.',
      'review_report': 'Yorumu şikayet et',
      'review_report_title': 'Bu yorumu neden şikayet ediyorsun?',
      'review_report_profanity': 'Küfür / nefret söylemi',
      'review_report_spam': 'Spam / reklam',
      'review_report_spoiler': 'İşaretlenmemiş spoiler',
      'review_report_harassment': 'Taciz',
      'review_report_other': 'Diğer',
      'review_reported': 'Şikayetin alındı. Teşekkürler.',
      'review_longpress_hint':
          'Şikayet etmek veya engellemek için yoruma basılı tut',
      'review_block_user': 'Kullanıcıyı engelle',
      'review_block_confirm_title': 'Bu kullanıcı engellensin mi?',
      'review_block_confirm_msg':
          'Yorumlarını ve aktivitesini artık görmezsin; varsa arkadaşlık da kaldırılır.',
      'review_blocked': 'Kullanıcı engellendi',
      'blocked_users_title': 'Engellenen Kullanıcılar',
      'blocked_users_subtitle':
          'Yorumlarını ve aktivitelerini gizlediğin kişiler',
      'blocked_users_empty': 'Engellediğin kullanıcı yok.',
      'blocked_users_unblock': 'Engeli Kaldır',
      'blocked_users_unblock_confirm_title': 'Engel kaldırılsın mı?',
      'blocked_users_unblock_confirm_msg':
          '{} kullanıcısının engeli kaldırılacak ve yorumları tekrar görünebilir.',
      'blocked_users_unblocked': 'Engel kaldırıldı',
      'blocked_users_load_error': 'Engellenenler yüklenemedi.',
      'review_delete': 'Yorumu sil',
      'review_delete_confirm': 'Bu yorum silinsin mi? Puanın korunacak.',
      'review_deleted': 'Yorum silindi',
      'rating_delete_with_comment_title': 'Puan kaldırılsın mı?',
      'rating_delete_with_comment_msg':
          'Puanı kaldırırsan yazdığın yorum da silinir.',
      'my_reviews_title': 'Yorumlarım',
      'my_reviews_empty': 'Henüz hiç yorum yazmadın.',
      'my_reviews_subtitle': 'Yazdığın tüm yorumlar tek yerde',
      'block': 'Engelle',
      'score_votes': '{} oy',
      'score_community_a11y': 'cinema+ üyelerinin %{} beğendi',

      // Match
      'match_title': 'Ortak Film Bul',
      'match_desc':
          'Arkadaşınla oda kodunu paylaşarak veya bir odaya katılarak birlikte ne izleyeceğinize karar verin.',
      'match_create_room': 'Oda Oluştur',
      'match_join_room': 'Odaya Katıl',
      'match_enter_code': 'Oda Kodu Girin',
      'match_invalid_code': 'Geçersiz oda kodu.',
      'match_room_code': 'Oda Kodu:',
      'match_waiting': 'Diğer kullanıcının katılması bekleniyor...',
      'match_start': 'Eşleştirmeyi Başlat',
      'match_found': 'EŞLEŞTİ!',
      'match_found_desc': 'İkinizin de beğendiği film/dizi:',
      'match_go_back': 'Geri Dön',
      'match_loading': 'Yükleniyor...',
      'match_swipe_left': 'Geç',
      'match_swipe_right': 'Beğen',
      'match_swiping_title': 'Eşleşme Kartları',
      'match_connecting': 'Bağlanıyor...',
      'match_status': 'Eşleşme Durumu',
      'swipe_disliked': 'Beğenilmedi',
      'mood_crime': 'Suç & polisiye',
      'browse_for_you_personal': 'Sana Özel',
      'tonight_title': 'Bu Gece Ne İzlesem?',
      'tonight_shuffle': 'Başka öner',
      'tonight_not_interested': 'İlgimi çekmedi',
      'dna_title': 'Sinema DNA\'n',
      'dna_banner_desc': 'Zevkinin kimliğini keşfet.',
      'dna_analyzing': 'Zevkin analiz ediliyor…',
      'dna_error': 'DNA oluşturulamadı',
      'dna_not_ready': 'DNA\'n henüz oluşuyor',
      'dna_not_ready_desc':
          'Birkaç film daha oyla, zevk kimliğin ortaya çıksın.',
      'dna_you_are': 'Sen',
      'dna_themes': 'Tekrar eden temaların',
      'dna_top_genres': 'Zirvedeki türlerin',
      'dna_signals': 'Zevkinin imzası',
      'dna_share': 'Paylaş',
      'dna_share_button': 'DNA\'nı paylaş',
      'dna_arch_dark_chronicler': 'Karanlık Anlatıcı',
      'dna_arch_emotion_seeker': 'Duygu Avcısı',
      'dna_arch_world_builder': 'Dünya Kâşifi',
      'dna_arch_adrenaline_junkie': 'Adrenalin Tutkunu',
      'dna_arch_joy_chaser': 'Neşe Avcısı',
      'dna_arch_truth_seeker': 'Gerçeğin Peşinde',
      'dna_arch_eternal_child': 'Sonsuz Çocuk',
      'dna_arch_genre_nomad': 'Tür Göçebesi',
      'dna_ess_dark_chronicler':
          'Gölgelere, gerilime ve ahlaki griliğe çekiliyorsun.',
      'dna_ess_emotion_seeker':
          'Kalbe dokunan, insanı anlatan hikâyelerin peşindesin.',
      'dna_ess_world_builder':
          'Yeni evrenler, imkânsız dünyalar seni çağırıyor.',
      'dna_ess_adrenaline_junkie': 'Tempo, aksiyon ve macera senin yakıtın.',
      'dna_ess_joy_chaser': 'Kahkaha ve hafiflik senin sığınağın.',
      'dna_ess_truth_seeker':
          'Gerçek hikâyeler ve geçmişin dersleri ilgini çekiyor.',
      'dna_ess_eternal_child': 'İçindeki çocuk hiç büyümedi — ve bu çok iyi.',
      'dna_ess_genre_nomad':
          'Tek bir türe sığmıyorsun; her renkten tadıyorsun.',
      'dna_ess_sec_dark_chronicler':
          'Gölgeler, gerilim ve ahlaki grilik de zevkini besliyor.',
      'dna_ess_sec_emotion_seeker':
          'Duygusal derinlik ve insani hikâyeler de seni cezbediyor.',
      'dna_ess_sec_world_builder':
          'Sıra dışı evrenler ve hayal gücü yüksek dünyalar da ilgini çekiyor.',
      'dna_ess_sec_adrenaline_junkie':
          'Tempo, aksiyon ve macera da senin heyecan kaynağın.',
      'dna_ess_sec_joy_chaser':
          'Hafiflik, neşe ve komedi de sığındığın limanlar arasında.',
      'dna_ess_sec_truth_seeker':
          'Gerçek hikâyeler ve yaşanmışlıklar da radarında.',
      'dna_ess_sec_eternal_child':
          'İçindeki büyümeyen çocuk da hikâyelerde yerini buluyor.',
      'dna_ess_sec_genre_nomad':
          'Farklı türlerin renkleri de zevkinde kendini gösteriyor.',
      'dna_era_modern': 'Modern çağ çocuğu — beğenilerinin {p} 2015 sonrası.',
      'dna_era_classic': 'Klasik ruh — eski sinemanın büyüsünü kovalıyorsun.',
      'dna_era_traveler':
          'Zaman gezgini — her dönemde kendini evinde hissediyorsun.',
      'dna_depth_deep':
          'Derin keşif avcısı — kalabalığın atladığı mücevherleri buluyorsun.',
      'dna_depth_zeit': 'Zeitgeist takipçisi — anın nabzını tutuyorsun.',
      'dna_depth_balanced':
          'Dengeli keşifçi — hem gişeyi hem gizli kalanı seviyorsun.',
      'dna_critic_tough':
          'Sert eleştirmen — puanlarının yalnızca {p} "Harika".',
      'dna_critic_generous':
          'Cömert kalp — iyi bir hikâyeye "Harika" demekten çekinmiyorsun.',
      'dna_critic_balanced':
          'Ölçülü eleştirmen — övgün de eleştirin de yerini biliyor.',
      'dna_blind': 'Kör noktan: {g} — sana pek hitap etmiyor.',
      'dna_shift': 'Zevkinin rotası: {from} → {to}.',
      'dna_accuracy':
          'Son önerilerdeki uyum oranınız: {p} — {n} öneri üzerinden.',
      'dna_share_header': 'Sinema DNA\'m: {a}',
      'dna_share_themes': 'Temalarım',
      'dna_share_cta': 'DNA\'na bak',
      'dna_share_cta_none': 'Sen de Sinema DNA\'nı keşfet!',
      'tonight_match': 'uyum',
      'reco_reason_seed': '{x} beğendiğin için',
      'reco_reason_friend': '{x} buna bayıldı',
      'match_find_suggestions': 'Ortak Önerileri Bul',
      'detail_seasons': 'Sezonlar',
      'mood_fantasy': 'Fantastik dünya',
      'mood_thought': 'Düşündürücü',
      'match_you': 'Sen',
      'search_title': 'Ara',
      'onboarding_subtitle_movie_genres':
          'Başlamak için ilgini çeken birkaç tür seç',
      'detail_reviews': 'Yorumlar',
      'semantics_remove_watchlist': 'İzleme listesinden çıkar',
      'match_empty_title': 'Sevdiğin yapımlara benzer içerikleri anında bul',
      'search_no_results': 'Sonuç bulunamadı.',
      'search_trending_movies': 'Trend Filmler',
      'detail_watchlist_add_short': 'Sonra İzle',
      'match_similar_to': '"{}" benzerleri',
      'search_trending_shows': 'Trend Diziler',
      'browse_error': 'İçerik yüklenirken bir hata oluştu.',
      'watchlist_empty_desc':
          'Bir film veya dizi detayında\n"İzleme Listesi" düğmesine dokun',
      'mood_classic': '90\'lar klasiği',
      'detail_trailer': 'Fragman',
      'match_no_similar': 'Benzer içerik bulunamadı',
      'detail_minutes': 'dk',
      'search_empty': 'Arama geçmişi boş.',
      'onboarding_search_empty_tv':
          'Favorilerini eklemek için\ndizi adıyla ara',
      'swipe_empty':
          'Değerlendirilecek içerik kalmadı. Favorilerinizi güncellemeyi deneyin!',
      'onboarding_subtitle_tv_genres': 'Devam etmek için ilgi alanlarını seç',
      'detail_no_reviews': 'Henüz yorum yazılmamış.',
      'mood_action': 'Aksiyon paketi',
      'semantics_undo': 'Değerlendirmeyi geri al',
      'browse_top_rated': 'En Yüksek Puanlılar',
      'match_select_at_least_one': 'İkiniz de en az 1 tür seçin',
      'detail_season_label': 'Sezon {}',
      'swipe_rate': 'Değerlendir',
      'onboarding_search_empty_movie':
          'Favorilerini eklemek için\nfilm adıyla ara',
      'match_together': 'Birlikte',
      'mood_thrill': 'Gerilim lazım',
      'browse_airing_today_tv': 'Bugün Yayında',
      'browse_api_unauthorized_desc':
          'Sunucu film servisiyle yetkilendirme sağlayamadı. Lütfen daha sonra tekrar deneyin.',
      'browse_api_missing_desc':
          'Sunucu taraflı servis yapılandırma hatası. Lütfen daha sonra tekrar deneyin.',
      'match_search_placeholder': 'Film veya dizi ara',
      'mood_romance': 'Romantik akşam',
      'browse_popular': 'Popüler',
      'browse_upcoming_coming': 'Yakında',
      'detail_seasons_count': 'sezon',
      'detail_similar': 'Benzer İçerikler',
      'match_friend': 'Arkadaş',
      'browse_movies': 'Filmler',
      'browse_trending_week': 'Bu Hafta Trend',
      'detail_share_text': 'Ne İzlesem önerisi: {}',
      'recommend_pick_friend': 'Kime önerelim?',
      'recommend_note_hint': 'Not ekle (isteğe bağlı)',
      'recommend_sent': 'Öneri gönderildi!',
      'recommend_need_login': 'Öneri göndermek için giriş yapmalısın.',
      'recommend_no_friends': 'Önce Sosyal sekmesinden arkadaş eklemelisin.',
      'browse_popular_tvs': 'Popüler Diziler',
      'browse_trending': 'Trendler',
      'detail_watchlist_remove': 'İzleme Listesinden Çıkar',
      'onboarding_search_hint_tv': 'Dizi ara...',
      'swipe_right_desc': 'Beğenmek için sağa kaydır',
      'search_clear': 'Temizle',
      'browse_conn_error': 'İnternet bağlantınızı kontrol edip tekrar deneyin.',
      'swipe_not_watched': 'İzlemedim',
      'browse_api_missing': 'Yapılandırma Hatası',
      'browse_popular_movies': 'Popüler Filmler',
      'detail_director': 'Yönetmen',
      'browse_random': 'Şansıma Bırak',
      'match_single_desc': 'Beğendiğin bir yapım gir, benzerlerini bulalım',
      'mood_light': 'Hafif & rahat',
      'watchlist_items': 'öğe',
      'browse_retry': 'Yeniden Dene',
      'search_failed': 'Arama başarısız oldu.',
      'swipe_hint': 'Kartı kaydırın',
      'match_together_desc': 'İkiniz de tür seçin, ortak önerileri bulalım',
      'mood_funny': 'Güldür beni',
      'swipe_left_desc': 'Geçmek için sola kaydır',
      'onboarding_search_hint_movie': 'Film ara...',
      'search_hint': 'Film veya dizi ara...',
      'browse_title': 'Keşfet',
      'detail_episodes_count': 'bölüm',
      'swipe_ratings_count': '{} değerlendirme',
      'search_history': 'Arama Geçmişi',
      'browse_now_playing_theaters': 'Vizyonda',
      'swipe_title': 'Değerlendir',
      'match_switch_match': 'Eşleştirmeye geç',
      'match_genres_count': '{} tür',
      'mood_cry': 'Ağlatacak bir şey',
      'mood_scary': 'Korku gecesi',
      'detail_directors': 'Yönetmenler',
      'detail_cast': 'Oyuncular',
      'detail_rating': 'Puan',
      'detail_watchlist_add': 'İzleme Listesine Ekle',
      'semantics_go_back': 'Geri dön',
      'browse_mood': 'Ruh haline göre',
      'browse_refresh': 'Yenile',
      'semantics_close': 'Kapat',
      'semantics_reset': 'Seçimleri sıfırla',
      'results_title': 'Öneriler',
      'theme_switch': 'Temayı değiştir',
      'watchlist_empty_title': 'Liste boş',
      'search_new_releases': 'Yeni Çıkanlar',
      'browse_api_unauthorized': 'Yetkilendirme Hatası (401)',
      'browse_offline_title': 'Çevrimdışısınız',
      'browse_offline_desc':
          'Lütfen internet bağlantınızı kontrol edin. Çevrimdışı modda yalnızca önbelleğe alınmış içerikleri görüntüleyebilirsiniz.',
      'browse_surprise': 'Sürpriz film',
      'detail_runtime': 'Süre',
      'browse_on_the_air_tv': 'Yayında',
      'swipe_liked': 'Beğenildi',
      'browse_top_rated_movies': 'En Yüksek Puanlı',
      'profile_rating': 'Değerlendirme',
      'mood_doc': 'Belgesel',
      'semantics_refresh': 'Tavsiyeleri yenile',
      'browse_tvs': 'Diziler',
      'search_quick_search': 'Hızlı Ara',
      'match_button': 'Eşleştir',
      'swipe_failed': 'Bağlantı kurulamadı.',
      'browse_friends_activity': 'Arkadaşlarından Son Sinyaller',
      'browse_rating_good': 'İyi dedi',
      'browse_rating_excellent': 'Harika dedi',
      'recap_journey_title': '{}\nSinema Yolculuğun',
      'recap_journey_desc':
          'Geçtiğimiz yıl boyunca yaptığın değerlendirmeleri senin için derledik. Keşfetmek için kaydır!',
      'recap_swipe_continue': 'Kaydır',
      'recap_what_watched': 'Neler İzledin?',
      'recap_total_titles': 'Tam {} Yapım',
      'recap_rated_sub': 'oyladın ve puanladın!',
      'recap_stat_amazing': 'Harika 🌟',
      'recap_stat_good': 'İyi 👍',
      'recap_stat_meh': 'Eh 😐',
      'recap_stat_awful': 'Berbat 👎',
      'recap_top_genres': 'EN SEVDİĞİN TÜRLER',
      'recap_no_taste_data': 'Henüz yeterli zevk profili oluşmadı.',
      'recap_highest_rated': 'EN BEĞENDİĞİN YAPIMLAR',
      'recap_rated_amazing': 'Harika Puan Verdiklerin',
      'recap_no_amazing_yet': 'Henüz hiçbir yapıma "Harika" dememişsin.',
      'recap_share_title': '{}\nSİNEMA YOLCULUĞUM',
      'recap_share_sub': '{} yapım oyladım',
      'recap_share_genres': 'Favori Türlerim:',
      'recap_share_button': 'Özetini Paylaş',
      'what_to': 'ne ',
      'watch': 'izlesem?',
      'personalize_recommendations': 'Önerileri Zevkine Göre Kişiselleştir',
      'complete_the_2minute_survey_fo':
          'Sana en uygun film ve dizileri bulmamız için 2 dakikalık analizi tamamla!',
      'you_are_offline_your_changes_w':
          'Çevrimdışısınız — Değişiklikleriniz senkronize edilecek',
      'no_common_genres': 'Ortak Tür Bulunamadı',
      'you_have_no_common_genres_sele':
          'İkinizin de seçtiği ortak bir tür bulunmuyor. Ortak bir tavsiye üretebilmemiz için lütfen en az bir ortak tür seçin.',
      'movie_match': 'Film Eşleştir',
      'movie_match_alt': 'Film Tabanlı',
      'with_friend': 'Arkadaşımla',
      'movie_matcher': 'Film Tabanlı Eşleştirme',
      'search_for_a_movie_or_tv_show_':
          'Sevdiğiniz bir filmi veya diziyi aratın, o içeriğin benzerlerini ve tür eşleşmelerini analiz edip zevkinize uygun yapımları listeleyelim.',
      'couch_mode_matcher': 'Aynı Cihazda Eşleştirme (Koltuk Modu)',
      'pass_the_phone_to_the_person_n':
          'Telefonu sırayla yanınızdaki kişiye verin. İkiniz de en sevdiğiniz film türlerini işaretleyin, ortak beğenebileceğiniz filmleri bulalım.',
      'player_1_you_select_your_favor':
          '👉 1. Kişi (Sen): En sevdiğin türleri seç...',
      'player_2_friend_now_its_your_t':
          '👉 2. Kişi (Arkadaşın): Şimdi senin sıran...',
      'common_match': 'Ortak Beğeni',
      'authentication_required': 'Giriş Yapmalısınız',
      'please_sign_in_to_view_watchli':
          'Arkadaşlarınızla ortak film kesişimlerini görebilmek için lütfen giriş yapın.',
      'no_friends_yet': 'Henüz Arkadaş Yok',
      'you_must_add_friends_first_to_':
          'Eşleşebilmek için önce arkadaş eklemelisiniz.',
      'add_manage_friends': 'Arkadaş Ekle / Yönet',
      'online_friend_match': 'Arkadaşımla Eşleş (Online)',
      'select_a_friend_to_find_common':
          'Eşleşmek istediğiniz bir arkadaşınızı seçin, ikinizin ortak izleme listelerini (watchlist) karşılaştırıp ortak ilgi alanlarınıza göre öneriler çıkaralım.',
      'select_a_friend_to_match_with':
          'Eşleşmek istediğiniz arkadaşınızı seçin:',
      'manage': 'Yönet',
      'no_common_movies': 'Ortak İzleme Listesi Boş',
      'neither_of_you_have_added_the_':
          'İkinizin de ortak izleme listesine eklediği film bulunmuyor.',
      'find_joint_recommendations': 'Ortak Tavsiye Bul',
      'hide_title': 'Yapımı Gizle',
      'are_you_sure_you_want_to_block':
          'Bu yapımı engellemek ve tüm listelerden kalıcı olarak gizlemek istediğinize emin misiniz?',
      'title_hidden_and_removed_from_':
          'Yapım gizlendi ve listelerden kaldırıldı.',
      'hide': 'Gizle',
      'undo': 'Geri Al',
      'block_and_hide_title': 'Yapımı Engelle ve Gizle',
      'recommend_to_friend': 'Arkadaşına Öner',
      'match_details': 'Uyum Detayları',
      'personal_taste_match': 'Kişisel Beğeni Uyumu',
      'tmdb_rating': 'TMDB Puanı',
      'cinema_member_score': 'cinema+ Üye Skoru',
      'review_saved_successfully': 'Yorumunuz kaydedildi',
      'saved': 'Kaydedildi ✔',
      'filmography': 'FİLMOGRAFİ',
      'do_you_want_to_delete_this_rat':
          'Bu filmin değerlendirmesini silmek ve geçmişinizden çıkarmak istiyor musunuz?',
      'delete': 'Sil',
      'your_cinema_recap': 'Sinema Özetin Hazır!',
      'discover_your_cinema_journey_o': 'Yılın sinema yolculuğunu keşfet.',
      'see_taste_matches_manage_reque':
          'Zevk uyumunuzu görün, istekleri ve arkadaş akışını yönetin.',
      'see_all': 'Tümünü Gör',
      'filters_out_deadpool_euphoria_':
          'Deadpool, Euphoria vb. +18 olgun içerikleri listelerden filtreler.',
      'active': ' (Aktif)',
      'filter': 'Filtrele',
      'year': 'Yıl',
      'language': 'DİL',
      'try_different_filters': 'Farklı filtreler dene',
      'advanced_filters': 'Gelişmiş Filtreler',
      'country_region': 'ÜLKE / BÖLGE',
      'platform': 'PLATFORM',
      'minimum_tmdb_score': 'MİNİMUM TMDB PUANI',
      'filter_and_list': 'Filtrele ve Listele',
      'please_enter_a_username': 'Lütfen kullanıcı adı girin.',
      'profile_updated_successfully': 'Profil başarıyla güncellendi.',
      'friend_request_sent':
          'Arkadaşlık isteği gönderildi. Karşı taraf onaylayınca arkadaş olacaksınız.',
      'friend_request_accepted':
          'Arkadaşlık isteği kabul edildi. Artık arkadaşsınız.',
      'friend_request_declined': 'İstek silindi.',
      'friend_request_withdrawn': 'İstek geri çekildi.',
      'friend_removed': 'Arkadaşlıktan çıkarıldı.',
      'social_network': 'Sosyal Ağ',
      'requests': 'İstekler',
      'activity': 'Akış',
      'top_lists': 'Popüler',
      'top_lists_title': 'Popüler Listeler',
      'top_lists_empty':
          'Henüz herkese açık profil yok. Profilini paylaş, hareket başlasın!',
      'top_lists_likes': 'beğeni',
      'top_lists_you': 'Sen',
      'top_lists_view_profile': 'Listeye bak',
      'customize_profile': 'Profilini Özelleştir',
      'username_username': 'Kullanıcı Adı (@username)',
      'public_profile': 'Profilim Halka Açık Olsun',
      'when_disabled_your_profile_can':
          'Kapalıyken profiliniz internette paylaşılamaz.',
      'save_settings': 'Kaydet',
      'username_or_email': 'Kullanıcı adı veya e-posta...',
      'no_friends_added_yet': 'Henüz arkadaşınız yok.',
      'remove_friend': 'Arkadaşı Çıkar',
      'remove': 'Çıkar',
      'no_pending_requests': 'Bekleyen istek bulunmuyor.',
      'received_requests': 'Gelen İstekler',
      'sent_requests': 'Gönderilen İstekler',
      'pending': 'Bekliyor',
      'no_friend_activity_yet': 'Henüz arkadaş aktivitesi yok.',
      'recommended_to_you': 'Sana Önerilenler',
      'cinema_taste_match': 'Sinema Zevki Uyumu',
      'no_activity_from_this_friend_y':
          'Bu arkadaşın henüz bir aktivitesi yok.',
      'error_saving_rating': 'Puan kaydedilirken hata oluştu.',
      'error_undoing_rating': 'İşlem geri alınırken hata oluştu.',
      'content_filters': 'İçerik Filtreleri',
      'language_region': 'DİL / ÜLKE',
      'streaming_platforms': 'DİJİTAL YAYIN PLATFORMU',
      'all': '🎬 Tümü',
      'no_more_content': 'İçerik Kalmadı',
      'loading_more': 'Daha fazla yükleniyor...',
      'no_more_content_matches_your_f':
          'Filtrenize uygun başka içerik kalmadı.\nFiltreleri temizleyerek devam edebilirsiniz.',
      'discovery_gestures': 'Keşfetme Hareketleri',
      'swipe_cards_to_train_our_recom':
          'Kartları kaydırarak zevk analizi motorumuzu eğitin!',
      'swipe_right': 'Sağa Kaydır',
      'liked_good_or_amazing': 'Beğendim (İyi veya Harika)',
      'swipe_left': 'Sola Kaydır',
      'disliked_meh_or_awful': 'Beğenmedim (Eh veya Berbat)',
      'tap_card': 'Karta Dokun',
      'view_details_trailer_cast': 'Detaylar, Fragman ve Oyuncular',
      'got_it_lets_start': 'Anladım, Keşfetmeye Başla!',
      'an_error_occurred_while_loadin': 'Yüklenirken bir hata oluştu.',
      'remove_from_watchlist': 'Listeden çıkarılsın mı?',
      'your_common_watchlist_intersec': 'Ortak İzleme Listeniz ({} Film/Dizi)',
      'title_removed_from_watchlist': '{} izleme listesinden çıkarıldı.',
      'synergy_score_match': '%{} Uyumlu',
      'error_occurred_msg': 'Hata oluştu: {}',
      'share_profile_text':
          'Beni Ne İzlesem uygulamasında takip et! İzleme listeme ve favorilerime buradan bakabilirsin: {}',
      'profile_share': 'Paylaş',
      'profile_share_message':
          'Beni Ne İzlesem uygulamasında takip et! İzleme listeme ve favorilerime buradan bakabilirsin: {}',
      'profile_share_no_username':
          'Profilinizi paylaşmak için profil ayarlarından kullanıcı adı belirleyin.',
      'taste_score_match': '%{} uyum',
      'remove_friend_confirm_msg':
          '{} arkadaş listenizden çıkarılacak. Emin misiniz?',
      'recommended_by_user': '{} önerdi',
      'friend_taste_match_desc': 'Bu arkadaşınızla ortak beğeni oranınız %{}.',
      'active_count_label': ' ({} Aktif)',
      'sync_error_message':
          'Eşitleme başarısız oldu. Değişiklikleriniz bu cihazda güvende.',
      'sync_retry': 'Tekrar Dene',
      'retry': 'Tekrar dene',
      'splash_tagline': ' | Ne İzlesem?',
      'web_profile': 'Web Profili',
      'social_customize_desc':
          'Arkadaşlarınızı eklemek ve sinema uyumunuzu görmek için bir kullanıcı adı belirleyin.',
      'social_set_username': 'Kullanıcı Adı Belirle',
      'browse_surprise_title': 'Şanslı Seçim 🎲',
      'browse_surprise_desc':
          'Bu zar butonu, puanladığınız filmlerden yola çıkarak zevklerinize uygun rastgele bir film seçer. "Şaşırt beni" demek istediğinizde kullanabilirsiniz!',
      'recap_share_template':
          '🎬 Ne İzlesem? {year} Sinematik Özetim!\n\nBu yıl tam {total} film/dizi oyladım! 🍿\nFavori Türlerim:\n{genres}\n\n{link_section}\n#NeIzlesem #Wrapped{year}',
      'recap_share_link_yes': 'Profilime ve oylarıma göz at: {url}',
      'recap_share_link_no': 'Sen de oylarını ver, özetini gör!',
      'change_language': 'Dil Seçimi',
      'got_it': 'Anladım',
    },
  };

  String get(String key) {
    final languageCode = locale.languageCode;
    if (_localizedValues[languageCode]?.containsKey(key) ?? false) {
      return _localizedValues[languageCode]![key]!;
    }
    if (_localizedValues['en']?.containsKey(key) ?? false) {
      return _localizedValues['en']![key]!;
    }
    return key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'tr'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
