import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static const List<Locale> supportedLocales = [
    Locale('tr', 'TR'),
    Locale('en', 'US'),
  ];

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'What to Watch?',
      'tagline': 'WHAT TO WATCH?',
      'tab_browse': 'Browse',
      'tab_swipe': 'Rate',
      'tab_match': 'Match',
      'tab_together': 'Together',
      'together_match': 'Match',
      'together_friends': 'Friends',
      'together_desc': 'Discover, match and share with friends.',
      'together_social_title': 'Social & Friends',
      'together_social_desc': 'Friends, requests and activity feed',
      'together_friend_match_title': 'Friend Match',
      'together_friend_match_desc': 'See shared likes and recommendations',
      'together_couch_title': 'Couch Mode',
      'together_couch_desc': 'On one phone',
      'together_similar_title': 'Find Similar',
      'together_similar_desc': 'Discover titles similar to one you love',
      'tab_search': 'Search',
      'tab_profile': 'Profile',

      // Onboarding
      'onboarding_loading': 'Preparing...',
      'onboarding_quick_rating': 'Quick rating',
      'onboarding_skip': 'Skip',
      'onboarding_not_watched': 'Not Watched',
      'onboarding_title_movie_genres': 'Which movie genres do you like?',
      'onboarding_title_tv_genres': 'Which TV show genres do you like?',
      'onboarding_title_fav_movies': 'Select your top 3 favorite movies',
      'onboarding_title_fav_tvs': 'Select your top 3 favorite TV shows',
      'onboarding_title_rating': 'Quick Rating',
      'onboarding_search_hint': 'Search...',
      'onboarding_fav_desc': 'Optional — you can add up to 3 favorites.',
      'onboarding_next': 'Continue',
      'onboarding_finish': 'Start',
      'onboarding_selected': 'selected',
      'onboarding_movie': 'Movie',
      'onboarding_tv': 'TV Show',
      'onboarding_done': 'Done',
      'swipe_recommended': 'For You',

      // Profile
      'profile_reset_title': 'Reset All Data',
      'profile_reset_content':
          'Ratings, reviews, watchlist, preferences, and cloud backups will be permanently reset, and you will be logged out. Continue?',
      'profile_cancel': 'Cancel',
      'profile_reset': 'Reset',
      'profile_reset_failed_title': 'Reset Failed',
      'profile_reset_failed_content':
          'Failed to delete cloud data. Please check your connection and try again.',
      'ok': 'OK',
      'auth_title_login': 'Sign In',
      'auth_title_register': 'Sign Up',
      'auth_email': 'Email Address',
      'auth_password': 'Password',
      'auth_display_name': 'Display Name',
      'auth_button_login': 'Login',
      'auth_button_register': 'Register',
      'auth_toggle_to_register': "Don't have an account? Sign Up",
      'auth_toggle_to_login': 'Already have an account? Sign In',
      'sync_title': 'Cloud Backup',
      'sync_desc':
          'Keep your watchlist, ratings, and history synced safely in the cloud.',
      'sync_now': 'Sync Now',
      'sync_success': 'Synchronized successfully',
      'sync_last': 'Last synced: ',
      'auth_logout': 'Sign Out',
      'auth_delete_account': 'Delete Account',
      'auth_delete_confirm':
          'This will permanently delete your account and all associated cloud data. Are you sure?',
      'auth_forgot_password_link': 'Forgot Password?',
      'auth_forgot_title': 'Forgot Password',
      'auth_forgot_email_desc':
          'Enter your registered email address to receive a password reset code.',
      'auth_forgot_code_title': 'Verify Code',
      'auth_forgot_code_desc':
          'Enter the 6-digit verification code sent to your email.',
      'auth_forgot_reset_title': 'Reset Password',
      'auth_forgot_reset_desc':
          'Set a new password of at least 8 characters for your account.',
      'auth_forgot_label_code': '6-Digit Verification Code',
      'auth_forgot_label_new_pass': 'New Password',
      'auth_forgot_btn_send_code': 'Send Code',
      'auth_forgot_btn_verify': 'Verify Code',
      'auth_forgot_btn_reset': 'Update Password',
      'auth_forgot_btn_back': 'Back',
      'auth_forgot_err_name_empty': 'Name field cannot be empty.',
      'auth_forgot_err_email_invalid': 'Enter a valid email.',
      'auth_forgot_err_code_length': 'Enter the complete 6-digit code.',
      'auth_forgot_err_pass_length': 'Password must be at least 8 characters.',
      'auth_forgot_success_reset':
          'Your password has been successfully reset. You can now sign in with your new password.',
      'profile_watchlist': 'Watchlist',
      'profile_stats': 'Stats',
      'profile_history': 'History',
      'profile_genres': 'Favorite Genres',
      'profile_total': 'Total',
      'profile_berbat': 'Awful',
      'profile_eh': 'Meh',
      'profile_iyi': 'Good',
      'profile_harika': 'Amazing',
      'profile_empty_watchlist':
          'You haven\'t added anything to your watchlist.',
      'profile_empty_history': 'You haven\'t rated anything yet.',
      'profile_no_genres': 'No preference signals yet.',
      'profile_rated_movies': 'Last Rated Items',
      'profile_clear_confirm': 'Clear all data',
      'profile_family_mode': 'Family Friendly Mode (PG-13)',
      'lang_ko': 'Korean Cinema',
      'lang_eu': 'European Cinema',
      'lang_en': 'Hollywood',
      'lang_tr': 'Turkish Cinema',
      'lang_ja': 'Japanese Cinema',
      'lang_hi': 'Bollywood',
      'lang_all': 'All',
      'lang_unknown': 'Unknown',
      'auth_register_subtitle': 'Create your account, keep your taste profile with you on all devices.',
      'auth_login_subtitle': 'Sign in to your account, continue from where you left off.',
      'auth_display_name_optional': 'Display Name (optional)',
      'auth_email_label': 'Email',
      'auth_password_label': 'Password',
      'profile_account': 'Account',
      'detail_where_to_watch': 'WHERE TO WATCH?',
      'detail_keywords': 'KEYWORDS',
      'detail_storyline': 'STORYLINE',
      'detail_collection': 'COLLECTION',
      'detail_rate_title': 'RATE THIS TITLE',
      'detail_your_review': 'YOUR REVIEW',

      // Review
      'review_spoiler': 'Contains Spoiler',
      'review_save': 'Save Review',
      'review_friends_title': 'Friends\' Reviews',
      'review_community_title': 'Community Reviews',
      'review_empty_first': 'Leave the first review',
      'review_no_friends': 'No reviews from friends yet',
      'review_comment_hint': 'Share your thoughts about this movie...',
      'review_spoiler_warning': 'Contains spoiler. Tap to view.',
      'score_votes': '{} votes',
      'score_community_a11y': '{}% of cinema+ members liked it',

      // Match
      'match_title': 'Match with Friend',
      'match_desc':
          'Decide what to watch together by sharing a room code or joining a room.',
      'match_create_room': 'Create Room',
      'match_join_room': 'Join Room',
      'match_enter_code': 'Enter Room Code',
      'match_invalid_code': 'Invalid room code.',
      'match_room_code': 'Room Code:',
      'match_waiting': 'Waiting for the other user to join...',
      'match_start': 'Start Match',
      'match_found': 'IT\'S A MATCH!',
      'match_found_desc': 'The content you both liked:',
      'match_go_back': 'Go Back',
      'match_loading': 'Loading...',
      'match_swipe_left': 'Skip',
      'match_swipe_right': 'Like',
      'match_swiping_title': 'Match Swiping',
      'match_connecting': 'Connecting...',
      'match_status': 'Match Status',

      // Swipe
      'swipe_title': 'Rate',
      'swipe_left_desc': 'Swipe left to skip',
      'swipe_right_desc': 'Swipe right to like',
      'swipe_empty':
          'No more content to rate. Try changing your favorites or check back later!',
      'swipe_hint': 'Swipe cards',

      // Browse
      'browse_title': 'Browse',
      'browse_retry': 'Retry',
      'browse_random': 'Surprise Me',
      'browse_mood': 'By Mood',
      'browse_trending': 'Trending',
      'browse_popular': 'Popular',
      'browse_top_rated': 'Top Rated',
      'browse_error': 'An error occurred while loading content.',
      'browse_conn_error': 'Check your internet connection and try again.',
      'browse_api_missing': 'Configuration Error',
      'browse_api_missing_desc':
          'Server-side service configuration error. Please try again later.',
      'browse_refresh': 'Refresh',
      'browse_movies': 'Movies',
      'browse_tvs': 'TV Shows',

      // Moods
      'mood_funny': 'Make me laugh',
      'mood_thrill': 'Need thrillers',
      'mood_cry': 'Make me cry',
      'mood_action': 'Action pack',
      'mood_light': 'Light & cozy',
      'mood_thought': 'Thought provoking',
      'mood_romance': 'Romantic evening',
      'mood_classic': '90\'s classic',
      'mood_scary': 'Scary night',
      'mood_doc': 'Documentary',
      'mood_fantasy': 'Fantasy world',
      'mood_crime': 'Crime & mystery',

      // Search
      'search_title': 'Search',
      'search_hint': 'Search movies or TV shows...',
      'search_empty': 'Search history is empty.',
      'search_history': 'Search History',
      'search_clear': 'Clear',
      'search_no_results': 'No results found.',

      // Movie Detail
      'detail_director': 'Director',
      'detail_directors': 'Directors',
      'detail_cast': 'Cast',
      'detail_reviews': 'Reviews',
      'detail_watchlist_add': 'Add to Watchlist',
      'detail_watchlist_remove': 'Remove from Watchlist',
      'detail_rating': 'Rating',
      'detail_runtime': 'Runtime',
      'detail_seasons': 'Seasons',
      'detail_no_reviews': 'No reviews yet.',
      'detail_similar': 'Similar Content',
      'detail_minutes': 'min',
      'detail_seasons_count': 'seasons',
      'detail_episodes_count': 'episodes',

      // Added / Missing
      'search_quick_search': 'Quick Search',
      'search_trending_movies': 'Trending Movies',
      'search_failed': 'Search failed.',
      'browse_popular_movies': 'Popular Movies',
      'browse_popular_tvs': 'Popular TV Shows',
      'browse_top_rated_movies': 'Top Rated',
      'browse_now_playing_theaters': 'In Theaters',
      'browse_airing_today_tv': 'Airing Today',
      'browse_on_the_air_tv': 'On The Air',
      'browse_upcoming_coming': 'Coming Soon',
      'browse_for_you_personal': 'For You',
      'browse_trending_week': 'Trending This Week',
      'browse_api_unauthorized_desc':
          'The server is unable to authenticate with the movie service. Please contact support.',
      'browse_offline_title': 'You are Offline',
      'browse_offline_desc':
          'Please check your internet connection and try again.',
      'browse_cta_title': 'What to Watch Tonight?',
      'browse_cta_subtitle':
          "Let's roll the dice and pick a random movie matched to your taste.",
      'swipe_rate': 'Rate',
      'swipe_not_watched': 'Not Watched',
      'swipe_liked': 'Liked',
      'swipe_disliked': 'Disliked',
      'swipe_failed': 'Connection failed.',
      'detail_trailer': 'Trailer',
      'detail_watchlist_add_short': 'Watchlist',
      'detail_share_text':
          'Check out this recommendation from What to Watch: {}',
      'detail_season_label': 'Season {}',
      'recommend_pick_friend': 'Who should we recommend it to?',
      'recommend_note_hint': 'Add a note (optional)',
      'recommend_sent': 'Recommendation sent!',
      'recommend_need_login': 'Sign in to send recommendations.',
      'recommend_no_friends': 'Add friends from the Social tab first.',
      'match_button': 'Match',
      'profile_rating': 'Rating',
      'semantics_refresh': 'Refresh recommendations',
      'semantics_go_back': 'Go back',
      'semantics_remove_watchlist': 'Remove from watchlist',
      'semantics_close': 'Close',
      'semantics_reset': 'Reset selections',
      'results_title': 'Recommendations',
      'theme_switch': 'Switch theme',
      'search_trending_shows': 'Trending TV Shows',
      'search_new_releases': 'New Releases',
      'semantics_undo': 'Undo rating',
      'match_together': 'Together',
      'match_switch_match': 'Switch to Match',
      'match_together_desc':
          'Both choose genres, we\'ll find common suggestions',
      'match_single_desc': 'Enter a title you like, we\'ll find similar ones',
      'match_search_placeholder': 'Search a movie or TV show',
      'match_empty_title': 'Find similar titles to what you love instantly',
      'match_no_similar': 'No similar content found',
      'match_you': 'You',
      'match_friend': 'Friend',
      'match_find_suggestions': 'Find Common Suggestions',
      'match_select_at_least_one': 'Both choose at least 1 genre',
      'match_genres_count': '{} genres',
      'match_similar_to': 'Similar to "{}"',
      'watchlist_empty_title': 'List is empty',
      'watchlist_empty_desc':
          'Tap the "Watchlist" button\non a movie or TV show detail screen',
      'swipe_ratings_count': '{} ratings',
      'watchlist_items': 'items',
      'onboarding_subtitle_movie_genres':
          'Select a few genres that interest you to get started',
      'onboarding_subtitle_tv_genres': 'Select your interests to continue',
      'onboarding_search_hint_movie': 'Search movie...',
      'onboarding_search_hint_tv': 'Search TV show...',
      'onboarding_search_empty_movie':
          'Search by movie name\nto add your favorites',
      'onboarding_search_empty_tv':
          'Search by TV show name\nto add your favorites',
      'browse_friends_activity': 'Recent Activity from Friends',
      'browse_rating_good': 'liked it',
      'browse_rating_excellent': 'loved it',
    },
    'tr': {
      'app_title': 'Ne İzlesem?',
      'tagline': 'NE İZLESEM?',
      'tab_browse': 'Keşfet',
      'tab_swipe': 'Değerlendir',
      'tab_match': 'Eşleştir',
      'tab_together': 'Birlikte',
      'together_match': 'Eşleştir',
      'together_friends': 'Arkadaşlar',
      'together_desc': 'Arkadaşlarınla keşfet, eşleş ve paylaş.',
      'together_social_title': 'Sosyal & Arkadaşlar',
      'together_social_desc': 'Arkadaşlar, istekler ve aktivite akışı',
      'together_friend_match_title': 'Arkadaşımla Eşleş',
      'together_friend_match_desc': 'Ortak beğeniler ve öneriler',
      'together_couch_title': 'Aynı Cihazda',
      'together_couch_desc': 'Tek telefonda',
      'together_similar_title': 'Benzer Film Bul',
      'together_similar_desc': 'Sevdiğin bir filme benzer yapımları keşfet',
      'tab_search': 'Ara',
      'tab_profile': 'Profil',

      // Onboarding
      'onboarding_loading': 'Hazırlanıyor...',
      'onboarding_quick_rating': 'Hızlı değerlendirme',
      'onboarding_skip': 'Atla',
      'onboarding_not_watched': 'İzlemedim',
      'onboarding_title_movie_genres': 'Hangi tür filmleri seversiniz?',
      'onboarding_title_tv_genres': 'Hangi tür dizileri seversiniz?',
      'onboarding_title_fav_movies': 'En sevdiğiniz 3 filmi seçin',
      'onboarding_title_fav_tvs': 'En sevdiğiniz 3 diziyi seçin',
      'onboarding_title_rating': 'Hızlı Değerlendirme',
      'onboarding_search_hint': 'Ara...',
      'onboarding_fav_desc':
          'İsteğe bağlı — en fazla 3 adet favorinizi ekleyebilirsiniz.',
      'onboarding_next': 'Devam',
      'onboarding_finish': 'Başla',
      'onboarding_selected': 'seçildi',
      'onboarding_movie': 'Film',
      'onboarding_tv': 'Dizi',
      'onboarding_done': 'Tamam',
      'swipe_recommended': 'Sana Özel',

      // Profile
      'profile_reset_title': 'Tüm Verileri Sıfırla',
      'profile_reset_content':
          'Değerlendirmeleriniz, yorumlarınız, izleme listeniz, tercihleriniz ve bulut yedekleriniz kalıcı olarak sıfırlanacak ve oturumunuz kapatılacaktır. Devam etmek istiyor musunuz?',
      'profile_cancel': 'Vazgeç',
      'profile_reset': 'Sıfırla',
      'profile_reset_failed_title': 'Sıfırlama Başarısız',
      'profile_reset_failed_content':
          'Sunucu verileri silinemedi. Lütfen internet bağlantınızı kontrol edip tekrar deneyin.',
      'ok': 'Tamam',
      'auth_title_login': 'Giriş Yap',
      'auth_title_register': 'Kayıt Ol',
      'auth_email': 'E-posta Adresi',
      'auth_password': 'Şifre',
      'auth_display_name': 'Görüntülenecek Ad',
      'auth_button_login': 'Giriş Yap',
      'auth_button_register': 'Kayıt Ol',
      'auth_toggle_to_register': 'Hesabınız yok mu? Kayıt Olun',
      'auth_toggle_to_login': 'Zaten hesabınız var mı? Giriş Yapın',
      'sync_title': 'Bulut Yedekleme',
      'sync_desc':
          'İzleme listenizi, puanlarınızı ve geçmişinizi güvenle bulutta saklayın.',
      'sync_now': 'Şimdi Eşitle',
      'sync_success': 'Başarıyla senkronize edildi',
      'sync_last': 'Son eşitleme: ',
      'auth_logout': 'Çıkış Yap',
      'auth_delete_account': 'Hesabı Sil',
      'auth_delete_confirm':
          'Bu işlem hesabınızı ve tüm bulut verilerinizi kalıcı olarak silecektir. Emin misiniz?',
      'auth_forgot_password_link': 'Şifremi Unuttum',
      'auth_forgot_title': 'Şifremi Unuttum',
      'auth_forgot_email_desc':
          'Şifre sıfırlama kodunu almak için kayıtlı e-posta adresinizi girin.',
      'auth_forgot_code_title': 'Kodu Doğrula',
      'auth_forgot_code_desc':
          'E-postanıza gönderilen 6 haneli doğrulama kodunu girin.',
      'auth_forgot_reset_title': 'Şifreyi Sıfırla',
      'auth_forgot_reset_desc':
          'Hesabınız için en az 8 karakterli yeni bir şifre belirleyin.',
      'auth_forgot_label_code': '6 Haneli Doğrulama Kodu',
      'auth_forgot_label_new_pass': 'Yeni Şifre',
      'auth_forgot_btn_send_code': 'Kod Gönder',
      'auth_forgot_btn_verify': 'Kodu Doğrula',
      'auth_forgot_btn_reset': 'Şifreyi Güncelle',
      'auth_forgot_btn_back': 'Geri Dön',
      'auth_forgot_err_name_empty': 'Ad alanı boş bırakılamaz.',
      'auth_forgot_err_email_invalid': 'Geçerli bir e-posta girin.',
      'auth_forgot_err_code_length': '6 haneli kodu eksiksiz girin.',
      'auth_forgot_err_pass_length': 'Parola en az 8 karakter olmalıdır.',
      'auth_forgot_success_reset':
          'Şifreniz başarıyla sıfırlandı. Yeni şifrenizle giriş yapabilirsiniz.',
      'profile_watchlist': 'İzleme Listesi',
      'profile_stats': 'İstatistikler',
      'profile_history': 'Geçmiş',
      'profile_genres': 'En Sevdiğin Türler',
      'profile_total': 'Toplam',
      'profile_berbat': 'Berbat',
      'profile_eh': 'Eh',
      'profile_iyi': 'İyi',
      'profile_harika': 'Harika',
      'profile_empty_watchlist': 'Henüz film veya dizi eklemediniz.',
      'profile_empty_history': 'Henüz değerlendirme yapmadınız.',
      'profile_no_genres': 'Tercih bulunamadı.',
      'profile_rated_movies': 'Son Değerlendirilenler',
      'profile_clear_confirm': 'Tüm verileri temizle',
      'profile_family_mode': 'Aile Dostu Mod (PG-13)',
      'lang_ko': 'Kore Sineması',
      'lang_eu': 'Avrupa Sineması',
      'lang_en': 'Hollywood',
      'lang_tr': 'Türk Sineması',
      'lang_ja': 'Japon Sineması',
      'lang_hi': 'Bollywood (Hint)',
      'lang_all': 'Tümü',
      'lang_unknown': 'Bilinmeyen',
      'auth_register_subtitle': 'Hesabını oluştur, zevk profilin her cihazda seninle olsun.',
      'auth_login_subtitle': 'Hesabına gir, kaldığın yerden devam et.',
      'auth_display_name_optional': 'Ad (isteğe bağlı)',
      'auth_email_label': 'E-posta',
      'auth_password_label': 'Parola',
      'profile_account': 'Hesap',
      'detail_where_to_watch': 'NEREDE İZLENİR?',
      'detail_keywords': 'ANAHTAR KELİMELER',
      'detail_storyline': 'KONU',
      'detail_collection': 'SERİNİN DİĞER FİLMLERİ',
      'detail_rate_title': 'BU YAPIMI PUANLA',
      'detail_your_review': 'YORUMUNUZ',

      // Review
      'review_spoiler': 'Spoiler İçerir',
      'review_save': 'Yorumu Kaydet',
      'review_friends_title': 'Arkadaşlarından Yorumlar',
      'review_community_title': 'Topluluk Yorumları',
      'review_empty_first': 'İlk yorumu sen bırak',
      'review_no_friends': 'Arkadaşlarından henüz yorum yok',
      'review_comment_hint': 'Bu yapım hakkındaki düşüncelerini paylaş...',
      'review_spoiler_warning': 'Spoiler içeriyor. Görmek için dokunun.',
      'score_votes': '{} oy',
      'score_community_a11y': 'cinema+ üyelerinin %{} beğendi',

      // Match
      'match_title': 'Ortak Film Bul',
      'match_desc':
          'Arkadaşınla oda kodunu paylaşarak veya bir odaya katılarak birlikte ne izleyeceğinize karar verin.',
      'match_create_room': 'Oda Oluştur',
      'match_join_room': 'Odaya Katıl',
      'match_enter_code': 'Oda Kodu Girin',
      'match_invalid_code': 'Geçersiz oda kodu.',
      'match_room_code': 'Oda Kodu:',
      'match_waiting': 'Diğer kullanıcının katılması bekleniyor...',
      'match_start': 'Eşleştirmeyi Başlat',
      'match_found': 'EŞLEŞTİ!',
      'match_found_desc': 'İkinizin de beğendiği film/dizi:',
      'match_go_back': 'Geri Dön',
      'match_loading': 'Yükleniyor...',
      'match_swipe_left': 'Geç',
      'match_swipe_right': 'Beğen',
      'match_swiping_title': 'Eşleşme Kartları',
      'match_connecting': 'Bağlanıyor...',
      'match_status': 'Eşleşme Durumu',
      'swipe_disliked': 'Beğenilmedi',
      'mood_crime': 'Suç & polisiye',
      'browse_for_you_personal': 'Sana Özel',
      'match_find_suggestions': 'Ortak Önerileri Bul',
      'detail_seasons': 'Sezonlar',
      'mood_fantasy': 'Fantastik dünya',
      'mood_thought': 'Düşündürücü',
      'match_you': 'Sen',
      'search_title': 'Ara',
      'onboarding_subtitle_movie_genres':
          'Başlamak için ilgini çeken birkaç tür seç',
      'detail_reviews': 'Yorumlar',
      'semantics_remove_watchlist': 'İzleme listesinden çıkar',
      'match_empty_title': 'Sevdiğin yapımlara benzer içerikleri anında bul',
      'search_no_results': 'Sonuç bulunamadı.',
      'search_trending_movies': 'Trend Filmler',
      'detail_watchlist_add_short': 'Sonra İzle',
      'match_similar_to': '"{}" benzerleri',
      'search_trending_shows': 'Trend Diziler',
      'browse_error': 'İçerik yüklenirken bir hata oluştu.',
      'watchlist_empty_desc':
          'Bir film veya dizi detayında\n"İzleme Listesi" düğmesine dokun',
      'mood_classic': '90\'lar klasiği',
      'detail_trailer': 'Fragman',
      'match_no_similar': 'Benzer içerik bulunamadı',
      'detail_minutes': 'dk',
      'search_empty': 'Arama geçmişi boş.',
      'onboarding_search_empty_tv':
          'Favorilerini eklemek için\ndizi adıyla ara',
      'swipe_empty':
          'Değerlendirilecek içerik kalmadı. Favorilerinizi güncellemeyi deneyin!',
      'onboarding_subtitle_tv_genres': 'Devam etmek için ilgi alanlarını seç',
      'detail_no_reviews': 'Henüz yorum yazılmamış.',
      'mood_action': 'Aksiyon paketi',
      'semantics_undo': 'Değerlendirmeyi geri al',
      'browse_top_rated': 'En Yüksek Puanlılar',
      'match_select_at_least_one': 'İkiniz de en az 1 tür seçin',
      'detail_season_label': 'Sezon {}',
      'swipe_rate': 'Değerlendir',
      'onboarding_search_empty_movie':
          'Favorilerini eklemek için\nfilm adıyla ara',
      'match_together': 'Birlikte',
      'mood_thrill': 'Gerilim lazım',
      'browse_airing_today_tv': 'Bugün Yayında',
      'browse_api_unauthorized_desc':
          'Sunucu film servisiyle yetkilendirme sağlayamadı. Lütfen daha sonra tekrar deneyin.',
      'browse_api_missing_desc':
          'Sunucu taraflı servis yapılandırma hatası. Lütfen daha sonra tekrar deneyin.',
      'match_search_placeholder': 'Film veya dizi ara',
      'mood_romance': 'Romantik akşam',
      'browse_popular': 'Popüler',
      'browse_upcoming_coming': 'Yakında',
      'detail_seasons_count': 'sezon',
      'detail_similar': 'Benzer İçerikler',
      'match_friend': 'Arkadaş',
      'browse_movies': 'Filmler',
      'browse_trending_week': 'Bu Hafta Trend',
      'detail_share_text': 'Ne İzlesem önerisi: {}',
      'recommend_pick_friend': 'Kime önerelim?',
      'recommend_note_hint': 'Not ekle (isteğe bağlı)',
      'recommend_sent': 'Öneri gönderildi!',
      'recommend_need_login': 'Öneri göndermek için giriş yapmalısın.',
      'recommend_no_friends': 'Önce Sosyal sekmesinden arkadaş eklemelisin.',
      'browse_popular_tvs': 'Popüler Diziler',
      'browse_trending': 'Trendler',
      'detail_watchlist_remove': 'İzleme Listesinden Çıkar',
      'onboarding_search_hint_tv': 'Dizi ara...',
      'swipe_right_desc': 'Beğenmek için sağa kaydır',
      'search_clear': 'Temizle',
      'browse_conn_error': 'İnternet bağlantınızı kontrol edip tekrar deneyin.',
      'swipe_not_watched': 'İzlemedim',
      'browse_api_missing': 'Yapılandırma Hatası',
      'browse_popular_movies': 'Popüler Filmler',
      'detail_director': 'Yönetmen',
      'browse_random': 'Şansıma Bırak',
      'match_single_desc': 'Beğendiğin bir yapım gir, benzerlerini bulalım',
      'mood_light': 'Hafif & rahat',
      'watchlist_items': 'öğe',
      'browse_retry': 'Yeniden Dene',
      'search_failed': 'Arama başarısız oldu.',
      'swipe_hint': 'Kartı kaydırın',
      'match_together_desc': 'İkiniz de tür seçin, ortak önerileri bulalım',
      'mood_funny': 'Güldür beni',
      'swipe_left_desc': 'Geçmek için sola kaydır',
      'onboarding_search_hint_movie': 'Film ara...',
      'search_hint': 'Film veya dizi ara...',
      'browse_title': 'Keşfet',
      'detail_episodes_count': 'bölüm',
      'swipe_ratings_count': '{} değerlendirme',
      'search_history': 'Arama Geçmişi',
      'browse_now_playing_theaters': 'Vizyonda',
      'swipe_title': 'Değerlendir',
      'match_switch_match': 'Eşleştirmeye geç',
      'match_genres_count': '{} tür',
      'mood_cry': 'Ağlatacak bir şey',
      'mood_scary': 'Korku gecesi',
      'detail_directors': 'Yönetmenler',
      'detail_cast': 'Oyuncular',
      'detail_rating': 'Puan',
      'detail_watchlist_add': 'İzleme Listesine Ekle',
      'semantics_go_back': 'Geri dön',
      'browse_mood': 'Ruh haline göre',
      'browse_refresh': 'Yenile',
      'semantics_close': 'Kapat',
      'semantics_reset': 'Seçimleri sıfırla',
      'results_title': 'Öneriler',
      'theme_switch': 'Temayı değiştir',
      'watchlist_empty_title': 'Liste boş',
      'search_new_releases': 'Yeni Çıkanlar',
      'browse_api_unauthorized': 'Yetkilendirme Hatası (401)',
      'browse_offline_title': 'Çevrimdışısınız',
      'browse_offline_desc':
          'Lütfen internet bağlantınızı kontrol edin. Çevrimdışı modda yalnızca önbelleğe alınmış içerikleri görüntüleyebilirsiniz.',
      'browse_cta_title': 'Bu Akşam Ne İzlesem?',
      'browse_cta_subtitle':
          'Zevkine uygun rastgele bir film seçelim. Şansına ne çıkacak?',
      'detail_runtime': 'Süre',
      'browse_on_the_air_tv': 'Yayında',
      'swipe_liked': 'Beğenildi',
      'browse_top_rated_movies': 'En Yüksek Puanlı',
      'profile_rating': 'Değerlendirme',
      'mood_doc': 'Belgesel',
      'semantics_refresh': 'Tavsiyeleri yenile',
      'browse_tvs': 'Diziler',
      'search_quick_search': 'Hızlı Ara',
      'match_button': 'Eşleştir',
      'swipe_failed': 'Bağlantı kurulamadı.',
      'browse_friends_activity': 'Arkadaşlarından Son Sinyaller',
      'browse_rating_good': 'İyi dedi',
      'browse_rating_excellent': 'Harika dedi',
    },
  };

  String get(String key) {
    final languageCode = _localizedValues.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';
    return _localizedValues[languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'tr'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
