// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvru5fje5OcEvQkRqIU_RtFIa7_sKJFls',
    appId: '1:925394401867:web:1da197e7ee91499517abce',
    messagingSenderId: '925394401867',
    projectId: 'cinema-6bdc3',
    authDomain: 'cinema-6bdc3.firebaseapp.com',
    storageBucket: 'cinema-6bdc3.firebasestorage.app',
    measurementId: 'G-QH9RR9KBLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy09fo_miRIKdyNI4-dT2pGWzzN6grTJQ',
    appId: '1:925394401867:android:86d4b03fd3b301c017abce',
    messagingSenderId: '925394401867',
    projectId: 'cinema-6bdc3',
    storageBucket: 'cinema-6bdc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnu-ACXZibICqst8fp9bOleIxebRmX4Eo',
    appId: '1:925394401867:ios:e45718ae801e471c17abce',
    messagingSenderId: '925394401867',
    projectId: 'cinema-6bdc3',
    storageBucket: 'cinema-6bdc3.firebasestorage.app',
    iosBundleId: 'com.example.neIzlesem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnu-ACXZibICqst8fp9bOleIxebRmX4Eo',
    appId: '1:925394401867:ios:e45718ae801e471c17abce',
    messagingSenderId: '925394401867',
    projectId: 'cinema-6bdc3',
    storageBucket: 'cinema-6bdc3.firebasestorage.app',
    iosBundleId: 'com.example.neIzlesem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvru5fje5OcEvQkRqIU_RtFIa7_sKJFls',
    appId: '1:925394401867:web:cca7fc49e94220fb17abce',
    messagingSenderId: '925394401867',
    projectId: 'cinema-6bdc3',
    authDomain: 'cinema-6bdc3.firebaseapp.com',
    storageBucket: 'cinema-6bdc3.firebasestorage.app',
    measurementId: 'G-56SD1W8987',
  );
}
